<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Official Quartz integration for Sentry - Open-source error tracking that helps developers monitor and fix crashes in real time.</Description>
    <PackageTags>$(PackageTags);Quartz</PackageTags>
    <TargetFrameworks>net10.0;</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <SignAssembly>false</SignAssembly>
  </PropertyGroup>

  <PropertyGroup Condition="'$(EnableAot)' == 'true'">
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Quartz" Version="4.0.0-alpha.1" />
    <ProjectReference Include="..\Sentry.AspNetCore\Sentry.AspNetCore.csproj" />
    <ProjectReference Include="..\Sentry\Sentry.csproj" />
  </ItemGroup>

  <ItemGroup>
<!--    <InternalsVisibleTo Include="Sentry.Quartz.Tests" PublicKey="$(SentryPublicKey)" />-->
  </ItemGroup>

</Project>
