version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.AspNetCore.Diagnostics.Abstractions
    versions:
    - "> 2.1.0, < 3"
  - dependency-name: Microsoft.AspNetCore.Hosting
    versions:
    - "> 2.1.0"
  - dependency-name: Microsoft.AspNetCore.Mvc.Testing
    versions:
    - "> 2.1.1"
  - dependency-name: Microsoft.AspNetCore.Routing.Abstractions
    versions:
    - "> 2.1.0"
  - dependency-name: Microsoft.AspNetCore.TestHost
    versions:
    - "> 2.1.1"
  - dependency-name: Microsoft.Extensions.Configuration.Binder
    versions:
    - "> 2.1.0"
  - dependency-name: Microsoft.Extensions.Configuration.CommandLine
    versions:
    - "> 2.1.1"
  - dependency-name: Microsoft.Extensions.Configuration.Json
    versions:
    - ">= 3.a, < 4"
  - dependency-name: Microsoft.Extensions.DependencyInjection
    versions:
    - "> 2.1.0"
  - dependency-name: Microsoft.Extensions.Hosting
    versions:
    - "> 2.1.1"
  - dependency-name: Microsoft.Extensions.Logging.Configuration
    versions:
    - "> 2.1.0"
  - dependency-name: Microsoft.Extensions.Logging.Console
    versions:
    - "> 2.1.1"
  - dependency-name: NLog
    versions:
    - "> 4.5.11, < 5"
  - dependency-name: Serilog
    versions:
    - "> 2.7.1"
  - dependency-name: System.Diagnostics.DiagnosticSource
    versions:
    - "> 4.5.0, < 5"
  - dependency-name: Grpc.AspNetCore.Server.Reflection
    versions:
    - 2.35.0
    - 2.36.0
  - dependency-name: Grpc.Net.Client
    versions:
    - 2.35.0
    - 2.36.0
  - dependency-name: Google.Protobuf
    versions:
    - 3.15.3
    - 3.15.4
    - 3.15.5
    - 3.15.6
    - 3.15.7
  - dependency-name: Amazon.Lambda.AspNetCoreServer
    versions:
    - 5.3.1
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
  - dependency-name: AWSSDK.Extensions.NETCore.Setup
    versions:
    - 3.3.101
