version: 2
updates:
- package-ecosystem: "dotnet-sdk"
  directory: "/"
  schedule:
    interval: "weekly"
  open-pull-requests-limit: 1

- package-ecosystem: nuget
  directory: "/samples"
  schedule:
    interval: monthly
  open-pull-requests-limit: 2

- package-ecosystem: nuget
  directory: "/test"
  schedule:
    interval: weekly
  open-pull-requests-limit: 2

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  ignore:
  - dependency-name: "gradle/actions/setup-gradle"
    versions: '>= 6.0.0' # license change: the bundled 'gradle-actions-caching' component is licensed and governed by a separate license (no longer MIT)

- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "weekly"
