global using DiffEngine;
global using Microsoft.Data.SqlClient;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.EntityFrameworkCore.Diagnostics.Internal;
global using Microsoft.Extensions.Logging;
global using Sentry.DiagnosticSource.IntegrationTests.EF;
global using Sentry.Extensions.Logging;
global using Sentry.Internal.DiagnosticSource;
