coverage:
  status:
    changes: false
    project:
      default:
        informational: true
    patch: off
  ignore:
    - "benchmarks/**/*"
    - "modules/**/*"
    - "samples/**/*"
    - "test/**/*"
  range: 0..100
  round: down
  precision: 2
