minVersion: 1.1.1
changelogPolicy: auto
targets:
  - name: nuget
  - name: github
  - name: registry
    sdks:
      nuget:Sentry:
      nuget:Sentry.AspNetCore:
      nuget:Sentry.AspNetCore.Grpc:
      nuget:Sentry.AspNet:
      nuget:Sentry.Azure.Functions.Worker:
      nuget:Sentry.DiagnosticSource:
      nuget:Sentry.EntityFramework:
      nuget:Sentry.Extensions.Logging:
      nuget:Sentry.Google.Cloud.Functions:
      nuget:Sentry.Log4Net:
      nuget:Sentry.Maui:
      nuget:Sentry.NLog:
      nuget:Sentry.OpenTelemetry:
      nuget:Sentry.Serilog:
