minVersion: 0.23.1
changelogPolicy: auto
targets:
  - name: nuget
  - name: github
  - name: registry
    sdks:
      nuget:Sentry:
      nuget:Sentry.Extensions.Logging:
      nuget:Sentry.AspNetCore:
      nuget:Sentry.AspNetCore.Grpc:
      nuget:Sentry.AspNet:
      nuget:Sentry.EntityFramework:
      nuget:Sentry.Diagnostics.DiagnosticSource:
      nuget:Sentry.Log4Net:
      nuget:Sentry.Serilog:
      nuget:Sentry.NLog:
