name: Checkout
description: Checkout code with pinned commit SHA
inputs:
  submodules:
    description: 'Whether to checkout submodules'
    required: false
    default: 'false'
  fetch-depth:
    description: 'Number of commits to fetch'
    required: false
    default: '1'
  sparse-checkout:
    description: 'Sparse checkout patterns'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        submodules: ${{ inputs.submodules }}
        fetch-depth: ${{ inputs.fetch-depth }}
        sparse-checkout: ${{ inputs.sparse-checkout }}