name: Download Artifact
description: Download artifact with pinned commit SHA
inputs:
  name:
    description: 'Artifact name'
    required: true
  path:
    description: 'Download path'
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Download Artifact
      uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}