name: Container test
description: Builds a minimal Native AOT app and runs it in a Docker container.
runs:
  using: composite
  steps:
    - name: Setup Local Source
      shell: bash
      run: |
        mkdir /tmp/local-packages
        cp ${{github.workspace}}/src/Sentry/bin/Release/Sentry.*.nupkg /tmp/local-packages/
        dotnet nuget add source /tmp/local-packages --name local-packages
        dotnet nuget list source

    - name: Setup Project
      shell: bash
      run: |
        dotnet --version
        dotnet new console --aot -o /tmp/hello-sentry
        cd /tmp/hello-sentry
        dotnet add package Sentry --prerelease --source /tmp/local-packages
        cat > Program.cs <<'EOF'
        SentrySdk.Init(options =>
        {
            options.Dsn = "https://foo@sentry.invalid/42";
            options.Debug = true;
        });
        Console.WriteLine("Hello, Sentry!");
        EOF

    - name: Publish Project
      shell: bash
      run: dotnet publish -p:EnableSdkContainerSupport=true -t:PublishContainer
      working-directory: /tmp/hello-sentry

    - name: Run Container
      shell: bash
      run: docker run hello-sentry
