// -----------------------------------------------------------------------------
// This file is auto-generated by Objective Sharpie and patched via the script
// at /scripts/patch-cocoa-bindings.cs.  Do not edit this file directly.
// If changes are required, update the script instead.
// -----------------------------------------------------------------------------

#nullable enable

using System;
using Foundation;
using ObjCRuntime;
using UIKit;

namespace Sentry.CocoaSdk;

// @interface SentryObjCDebugMeta : NSObject
[BaseType(typeof(NSObject))]
[Internal]
interface SentryObjCDebugMeta
{
    // @property (copy, nonatomic) NSString * _Nullable debugID;
    [NullAllowed, Export("debugID")]
    string DebugID { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable type;
    [NullAllowed, Export("type")]
    string Type { get; set; }

    // @property (copy, nonatomic) NSNumber * _Nullable imageSize;
    [NullAllowed, Export("imageSize", ArgumentSemantic.Copy)]
    NSNumber ImageSize { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable imageAddress;
    [NullAllowed, Export("imageAddress")]
    string ImageAddress { get; set; }

    // @property (assign, nonatomic) uint64_t imageAddressRaw;
    [Export("imageAddressRaw")]
    ulong ImageAddressRaw { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable imageVmAddress;
    [NullAllowed, Export("imageVmAddress")]
    string ImageVmAddress { get; set; }

    // @property (assign, nonatomic) uint64_t imageVmAddressRaw;
    [Export("imageVmAddressRaw")]
    ulong ImageVmAddressRaw { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable codeFile;
    [NullAllowed, Export("codeFile")]
    string CodeFile { get; set; }
}

// @interface SentryObjCFrame : NSObject
[BaseType(typeof(NSObject))]
[Internal]
interface SentryObjCFrame
{
    // @property (copy, nonatomic) NSString * _Nullable symbolAddress;
    [NullAllowed, Export("symbolAddress")]
    string SymbolAddress { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable fileName;
    [NullAllowed, Export("fileName")]
    string FileName { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable function;
    [NullAllowed, Export("function")]
    string Function { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable module;
    [NullAllowed, Export("module")]
    string Module { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable package;
    [NullAllowed, Export("package")]
    string Package { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable imageAddress;
    [NullAllowed, Export("imageAddress")]
    string ImageAddress { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable platform;
    [NullAllowed, Export("platform")]
    string Platform { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable instructionAddress;
    [NullAllowed, Export("instructionAddress")]
    string InstructionAddress { get; set; }

    // @property (copy, nonatomic) NSNumber * _Nullable lineNumber;
    [NullAllowed, Export("lineNumber", ArgumentSemantic.Copy)]
    NSNumber LineNumber { get; set; }

    // @property (copy, nonatomic) NSNumber * _Nullable columnNumber;
    [NullAllowed, Export("columnNumber", ArgumentSemantic.Copy)]
    NSNumber ColumnNumber { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable contextLine;
    [NullAllowed, Export("contextLine")]
    string ContextLine { get; set; }

    // @property (copy, nonatomic) NSNumber * _Nullable parentIndex;
    [NullAllowed, Export("parentIndex", ArgumentSemantic.Copy)]
    NSNumber ParentIndex { get; set; }

    // @property (copy, nonatomic) NSNumber * _Nullable sampleCount;
    [NullAllowed, Export("sampleCount", ArgumentSemantic.Copy)]
    NSNumber SampleCount { get; set; }

    // @property (copy, nonatomic) NSArray<NSString *> * _Nullable preContext;
    [NullAllowed, Export("preContext", ArgumentSemantic.Copy)]
    string[] PreContext { get; set; }

    // @property (copy, nonatomic) NSArray<NSString *> * _Nullable postContext;
    [NullAllowed, Export("postContext", ArgumentSemantic.Copy)]
    string[] PostContext { get; set; }

    // @property (copy, nonatomic) NSNumber * _Nullable inApp;
    [NullAllowed, Export("inApp", ArgumentSemantic.Copy)]
    NSNumber InApp { get; set; }

    // @property (copy, nonatomic) NSNumber * _Nullable stackStart;
    [NullAllowed, Export("stackStart", ArgumentSemantic.Copy)]
    NSNumber StackStart { get; set; }

    // @property (copy, nonatomic) NSDictionary<NSString *,id> * _Nullable vars;
    [NullAllowed, Export("vars", ArgumentSemantic.Copy)]
    NSDictionary<NSString, NSObject> Vars { get; set; }
}

// @interface SentryObjCGeo : NSObject
[BaseType(typeof(NSObject))]
[Internal]
interface SentryObjCGeo
{
    // @property (copy, nonatomic) NSString * _Nullable city;
    [NullAllowed, Export("city")]
    string City { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable countryCode;
    [NullAllowed, Export("countryCode")]
    string CountryCode { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable region;
    [NullAllowed, Export("region")]
    string Region { get; set; }
}

// @interface SentryObjCHttpStatusCodeRange : NSObject
[BaseType(typeof(NSObject))]
[DisableDefaultCtor]
[Internal]
interface SentryObjCHttpStatusCodeRange
{
    // @property (readonly, nonatomic) NSInteger min;
    [Export("min")]
    nint Min { get; }

    // @property (readonly, nonatomic) NSInteger max;
    [Export("max")]
    nint Max { get; }

    // -(instancetype _Nonnull)initWithMin:(NSInteger)min max:(NSInteger)max;
    [Export("initWithMin:max:")]
    NativeHandle Constructor(nint min, nint max);

    // -(instancetype _Nonnull)initWithStatusCode:(NSInteger)statusCode;
    [Export("initWithStatusCode:")]
    NativeHandle Constructor(nint statusCode);
}

// @interface SentryObjCId : NSObject
[BaseType(typeof(NSObject))]
[Internal]
interface SentryObjCId
{
    // @property (readonly, copy, nonatomic) NSString * _Nonnull sentryIdString;
    [Export("sentryIdString")]
    string SentryIdString { get; }

    // @property (readonly, nonatomic, strong, class) SentryObjCId * _Nonnull empty;
    [Static]
    [Export("empty", ArgumentSemantic.Strong)]
    SentryObjCId Empty { get; }

    // -(instancetype _Nonnull)initWithUuid:(NSUUID * _Nonnull)uuid;
    [Export("initWithUuid:")]
    NativeHandle Constructor(NSUuid uuid);

    // -(instancetype _Nonnull)initWithUUIDString:(NSString * _Nonnull)uuidString;
    [Export("initWithUUIDString:")]
    NativeHandle Constructor(string uuidString);
}

// @interface SentryObjCMeasurementUnit : NSObject
[BaseType(typeof(NSObject))]
[DisableDefaultCtor]
[Internal]
interface SentryObjCMeasurementUnit
{
    // @property (readonly, copy, nonatomic) NSString * _Nonnull unit;
    [Export("unit")]
    string Unit { get; }

    // -(instancetype _Nonnull)initWithUnit:(NSString * _Nonnull)unit;
    [Export("initWithUnit:")]
    NativeHandle Constructor(string unit);

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull none;
    [Static]
    [Export("none", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit None { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull nanosecond;
    [Static]
    [Export("nanosecond", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Nanosecond { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull microsecond;
    [Static]
    [Export("microsecond", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Microsecond { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull millisecond;
    [Static]
    [Export("millisecond", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Millisecond { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull second;
    [Static]
    [Export("second", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Second { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull minute;
    [Static]
    [Export("minute", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Minute { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull hour;
    [Static]
    [Export("hour", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Hour { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull day;
    [Static]
    [Export("day", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Day { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull week;
    [Static]
    [Export("week", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Week { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull bit;
    [Static]
    [Export("bit", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Bit { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull byte;
    [Static]
    [Export("byte", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Byte { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull kilobyte;
    [Static]
    [Export("kilobyte", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Kilobyte { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull kibibyte;
    [Static]
    [Export("kibibyte", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Kibibyte { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull megabyte;
    [Static]
    [Export("megabyte", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Megabyte { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull mebibyte;
    [Static]
    [Export("mebibyte", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Mebibyte { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull gigabyte;
    [Static]
    [Export("gigabyte", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Gigabyte { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull gibibyte;
    [Static]
    [Export("gibibyte", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Gibibyte { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull terabyte;
    [Static]
    [Export("terabyte", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Terabyte { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull tebibyte;
    [Static]
    [Export("tebibyte", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Tebibyte { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull petabyte;
    [Static]
    [Export("petabyte", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Petabyte { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull pebibyte;
    [Static]
    [Export("pebibyte", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Pebibyte { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull exabyte;
    [Static]
    [Export("exabyte", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Exabyte { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull exbibyte;
    [Static]
    [Export("exbibyte", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Exbibyte { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull ratio;
    [Static]
    [Export("ratio", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Ratio { get; }

    // @property (readonly, copy, nonatomic, class) SentryObjCMeasurementUnit * _Nonnull percent;
    [Static]
    [Export("percent", ArgumentSemantic.Copy)]
    SentryObjCMeasurementUnit Percent { get; }
}

// @interface SentryObjCMechanismContext : NSObject
[BaseType(typeof(NSObject))]
[Internal]
interface SentryObjCMechanismContext
{
    // @property (nonatomic, strong) NSDictionary<NSString *,id> * _Nullable signal;
    [NullAllowed, Export("signal", ArgumentSemantic.Strong)]
    NSDictionary<NSString, NSObject> Signal { get; set; }

    // @property (nonatomic, strong) NSDictionary<NSString *,id> * _Nullable machException;
    [NullAllowed, Export("machException", ArgumentSemantic.Strong)]
    NSDictionary<NSString, NSObject> MachException { get; set; }

    // @property (nonatomic, strong) SentryObjCNSError * _Nullable error;
    [NullAllowed, Export("error", ArgumentSemantic.Strong)]
    SentryObjCNSError Error { get; set; }
}

// @interface SentryObjCMessage : NSObject
[BaseType(typeof(NSObject))]
[DisableDefaultCtor]
[Internal]
interface SentryObjCMessage
{
    // @property (readonly, copy, nonatomic) NSString * _Nonnull formatted;
    [Export("formatted")]
    string Formatted { get; }

    // @property (copy, nonatomic) NSString * _Nullable message;
    [NullAllowed, Export("message")]
    string Message { get; set; }

    // @property (nonatomic, strong) NSArray<NSString *> * _Nullable params;
    [NullAllowed, Export("params", ArgumentSemantic.Strong)]
    string[] Params { get; set; }

    // -(instancetype _Nonnull)initWithFormatted:(NSString * _Nonnull)formatted;
    [Export("initWithFormatted:")]
    NativeHandle Constructor(string formatted);
}

// @interface SentryObjCNSError : NSObject
[BaseType(typeof(NSObject))]
[DisableDefaultCtor]
[Internal]
interface SentryObjCNSError
{
    // @property (copy, nonatomic) NSString * _Nonnull domain;
    [Export("domain")]
    string Domain { get; set; }

    // @property (assign, nonatomic) NSInteger code;
    [Export("code")]
    nint Code { get; set; }

    // -(instancetype _Nonnull)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code;
    [Export("initWithDomain:code:")]
    NativeHandle Constructor(string domain, nint code);
}

// @interface SentryObjCRequest : NSObject
[BaseType(typeof(NSObject))]
[Internal]
interface SentryObjCRequest
{
    // @property (copy, nonatomic) NSNumber * _Nullable bodySize;
    [NullAllowed, Export("bodySize", ArgumentSemantic.Copy)]
    NSNumber BodySize { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable cookies;
    [NullAllowed, Export("cookies")]
    string Cookies { get; set; }

    // @property (nonatomic, strong) NSDictionary<NSString *,NSString *> * _Nullable headers;
    [NullAllowed, Export("headers", ArgumentSemantic.Strong)]
    NSDictionary<NSString, NSString> Headers { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable fragment;
    [NullAllowed, Export("fragment")]
    string Fragment { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable method;
    [NullAllowed, Export("method")]
    string Method { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable queryString;
    [NullAllowed, Export("queryString")]
    string QueryString { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable url;
    [NullAllowed, Export("url")]
    string Url { get; set; }
}

// @interface SentryObjCSpanId : NSObject
[BaseType(typeof(NSObject))]
[Internal]
interface SentryObjCSpanId
{
    // @property (readonly, copy, nonatomic) NSString * _Nonnull sentrySpanIdString;
    [Export("sentrySpanIdString")]
    string SentrySpanIdString { get; }

    // @property (readonly, nonatomic, strong, class) SentryObjCSpanId * _Nonnull empty;
    [Static]
    [Export("empty", ArgumentSemantic.Strong)]
    SentryObjCSpanId Empty { get; }

    // -(instancetype _Nonnull)initWithUuid:(NSUUID * _Nonnull)uuid;
    [Export("initWithUuid:")]
    NativeHandle Constructor(NSUuid uuid);

    // -(instancetype _Nonnull)initWithValue:(NSString * _Nonnull)value;
    [Export("initWithValue:")]
    NativeHandle Constructor(string value);
}

// @interface SentryObjCTraceHeader : NSObject
[BaseType(typeof(NSObject))]
[DisableDefaultCtor]
[Internal]
interface SentryObjCTraceHeader
{
    // @property (readonly, nonatomic, strong) SentryObjCId * _Nonnull traceId;
    [Export("traceId", ArgumentSemantic.Strong)]
    SentryObjCId TraceId { get; }

    // @property (readonly, nonatomic, strong) SentryObjCSpanId * _Nonnull spanId;
    [Export("spanId", ArgumentSemantic.Strong)]
    SentryObjCSpanId SpanId { get; }

    // @property (readonly, nonatomic) SentryObjCSampleDecision sampled;
    [Export("sampled")]
    SentryObjCSampleDecision Sampled { get; }

    // -(instancetype _Nonnull)initWithTraceId:(SentryObjCId * _Nonnull)traceId spanId:(SentryObjCSpanId * _Nonnull)spanId sampled:(SentryObjCSampleDecision)sampled;
    [Export("initWithTraceId:spanId:sampled:")]
    NativeHandle Constructor(SentryObjCId traceId, SentryObjCSpanId spanId, SentryObjCSampleDecision sampled);

    // -(NSString * _Nonnull)value;
    [Export("value")]
    string Value { get; }
}

// @interface SentryObjCAttachment : NSObject
[BaseType(typeof(NSObject))]
[DisableDefaultCtor]
[Internal]
interface SentryObjCAttachment
{
    // @property (readonly, nonatomic, strong) NSData * _Nullable data;
    [NullAllowed, Export("data", ArgumentSemantic.Strong)]
    NSData Data { get; }

    // @property (readonly, copy, nonatomic) NSString * _Nullable path;
    [NullAllowed, Export("path")]
    string Path { get; }

    // @property (readonly, copy, nonatomic) NSString * _Nonnull filename;
    [Export("filename")]
    string Filename { get; }

    // @property (readonly, copy, nonatomic) NSString * _Nullable contentType;
    [NullAllowed, Export("contentType")]
    string ContentType { get; }

    // @property (readonly, nonatomic) SentryObjCAttachmentType attachmentType;
    [Export("attachmentType")]
    SentryObjCAttachmentType AttachmentType { get; }

    // -(instancetype _Nonnull)initWithData:(NSData * _Nonnull)data filename:(NSString * _Nonnull)filename;
    [Export("initWithData:filename:")]
    NativeHandle Constructor(NSData data, string filename);

    // -(instancetype _Nonnull)initWithData:(NSData * _Nonnull)data filename:(NSString * _Nonnull)filename contentType:(NSString * _Nullable)contentType;
    [Export("initWithData:filename:contentType:")]
    NativeHandle Constructor(NSData data, string filename, [NullAllowed] string contentType);

    // -(instancetype _Nonnull)initWithPath:(NSString * _Nonnull)path;
    [Export("initWithPath:")]
    NativeHandle Constructor(string path);

    // -(instancetype _Nonnull)initWithPath:(NSString * _Nonnull)path filename:(NSString * _Nonnull)filename;
    [Export("initWithPath:filename:")]
    NativeHandle Constructor(string path, string filename);

    // -(instancetype _Nonnull)initWithPath:(NSString * _Nonnull)path filename:(NSString * _Nonnull)filename contentType:(NSString * _Nullable)contentType;
    [Export("initWithPath:filename:contentType:")]
    NativeHandle Constructor(string path, string filename, [NullAllowed] string contentType);

    // -(instancetype _Nonnull)initWithData:(NSData * _Nonnull)data filename:(NSString * _Nonnull)filename contentType:(NSString * _Nullable)contentType attachmentType:(SentryObjCAttachmentType)attachmentType;
    [Export("initWithData:filename:contentType:attachmentType:")]
    NativeHandle Constructor(NSData data, string filename, [NullAllowed] string contentType, SentryObjCAttachmentType attachmentType);

    // -(instancetype _Nonnull)initWithPath:(NSString * _Nonnull)path filename:(NSString * _Nonnull)filename contentType:(NSString * _Nullable)contentType attachmentType:(SentryObjCAttachmentType)attachmentType;
    [Export("initWithPath:filename:contentType:attachmentType:")]
    NativeHandle Constructor(string path, string filename, [NullAllowed] string contentType, SentryObjCAttachmentType attachmentType);
}

// @interface SentryObjCBreadcrumb : NSObject
[BaseType(typeof(NSObject))]
[Internal]
interface SentryObjCBreadcrumb
{
    // @property (nonatomic) SentryObjCLevel level;
    [Export("level", ArgumentSemantic.Assign)]
    SentryObjCLevel Level { get; set; }

    // @property (copy, nonatomic) NSString * _Nonnull category;
    [Export("category")]
    string Category { get; set; }

    // @property (nonatomic, strong) NSDate * _Nullable timestamp;
    [NullAllowed, Export("timestamp", ArgumentSemantic.Strong)]
    NSDate Timestamp { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable type;
    [NullAllowed, Export("type")]
    string Type { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable message;
    [NullAllowed, Export("message")]
    string Message { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable origin;
    [NullAllowed, Export("origin")]
    string Origin { get; set; }

    // @property (copy, nonatomic) NSDictionary<NSString *,id> * _Nullable data;
    [NullAllowed, Export("data", ArgumentSemantic.Copy)]
    NSDictionary<NSString, NSObject> Data { get; set; }

    // -(instancetype _Nonnull)initWithLevel:(SentryObjCLevel)level category:(NSString * _Nonnull)category;
    [Export("initWithLevel:category:")]
    NativeHandle Constructor(SentryObjCLevel level, string category);
}

// @interface SentryObjCException : NSObject
[BaseType(typeof(NSObject))]
[DisableDefaultCtor]
[Internal]
interface SentryObjCException
{
    // @property (copy, nonatomic) NSString * _Nullable value;
    [NullAllowed, Export("value")]
    string Value { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable type;
    [NullAllowed, Export("type")]
    string Type { get; set; }

    // @property (nonatomic, strong) SentryObjCMechanism * _Nullable mechanism;
    [NullAllowed, Export("mechanism", ArgumentSemantic.Strong)]
    SentryObjCMechanism Mechanism { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable module;
    [NullAllowed, Export("module")]
    string Module { get; set; }

    // @property (copy, nonatomic) NSNumber * _Nullable threadId;
    [NullAllowed, Export("threadId", ArgumentSemantic.Copy)]
    NSNumber ThreadId { get; set; }

    // @property (nonatomic, strong) SentryObjCStacktrace * _Nullable stacktrace;
    [NullAllowed, Export("stacktrace", ArgumentSemantic.Strong)]
    SentryObjCStacktrace Stacktrace { get; set; }

    // -(instancetype _Nonnull)initWithValue:(NSString * _Nullable)value type:(NSString * _Nullable)type;
    [Export("initWithValue:type:")]
    NativeHandle Constructor([NullAllowed] string value, [NullAllowed] string type);
}

// @interface SentryObjCMechanism : NSObject
[BaseType(typeof(NSObject))]
[DisableDefaultCtor]
[Internal]
interface SentryObjCMechanism
{
    // @property (copy, nonatomic) NSString * _Nonnull type;
    [Export("type")]
    string Type { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable desc;
    [NullAllowed, Export("desc")]
    string Desc { get; set; }

    // @property (nonatomic, strong) NSDictionary<NSString *,id> * _Nullable data;
    [NullAllowed, Export("data", ArgumentSemantic.Strong)]
    NSDictionary<NSString, NSObject> Data { get; set; }

    // @property (copy, nonatomic) NSNumber * _Nullable handled;
    [NullAllowed, Export("handled", ArgumentSemantic.Copy)]
    NSNumber Handled { get; set; }

    // @property (copy, nonatomic) NSNumber * _Nullable synthetic;
    [NullAllowed, Export("synthetic", ArgumentSemantic.Copy)]
    NSNumber Synthetic { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable helpLink;
    [NullAllowed, Export("helpLink")]
    string HelpLink { get; set; }

    // @property (nonatomic, strong) SentryObjCMechanismContext * _Nullable meta;
    [NullAllowed, Export("meta", ArgumentSemantic.Strong)]
    SentryObjCMechanismContext Meta { get; set; }

    // -(instancetype _Nonnull)initWithType:(NSString * _Nonnull)type;
    [Export("initWithType:")]
    NativeHandle Constructor(string type);
}

// @interface SentryObjCStacktrace : NSObject
[BaseType(typeof(NSObject))]
[DisableDefaultCtor]
[Internal]
interface SentryObjCStacktrace
{
    // @property (nonatomic, strong) NSArray<SentryObjCFrame *> * _Nonnull frames;
    [Export("frames", ArgumentSemantic.Strong)]
    SentryObjCFrame[] Frames { get; set; }

    // @property (nonatomic, strong) NSDictionary<NSString *,NSString *> * _Nonnull registers;
    [Export("registers", ArgumentSemantic.Strong)]
    NSDictionary<NSString, NSString> Registers { get; set; }

    // @property (copy, nonatomic) NSNumber * _Nullable snapshot;
    [NullAllowed, Export("snapshot", ArgumentSemantic.Copy)]
    NSNumber Snapshot { get; set; }

    // -(instancetype _Nonnull)initWithFrames:(NSArray<SentryObjCFrame *> * _Nonnull)frames registers:(NSDictionary<NSString *,NSString *> * _Nonnull)registers;
    [Export("initWithFrames:registers:")]
    NativeHandle Constructor(SentryObjCFrame[] frames, NSDictionary<NSString, NSString> registers);
}

// @interface SentryObjCThread : NSObject
[BaseType(typeof(NSObject))]
[DisableDefaultCtor]
[Internal]
interface SentryObjCThread
{
    // @property (copy, nonatomic) NSNumber * _Nullable threadId;
    [NullAllowed, Export("threadId", ArgumentSemantic.Copy)]
    NSNumber ThreadId { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable name;
    [NullAllowed, Export("name")]
    string Name { get; set; }

    // @property (nonatomic, strong) SentryObjCStacktrace * _Nullable stacktrace;
    [NullAllowed, Export("stacktrace", ArgumentSemantic.Strong)]
    SentryObjCStacktrace Stacktrace { get; set; }

    // @property (copy, nonatomic) NSNumber * _Nullable crashed;
    [NullAllowed, Export("crashed", ArgumentSemantic.Copy)]
    NSNumber Crashed { get; set; }

    // @property (copy, nonatomic) NSNumber * _Nullable current;
    [NullAllowed, Export("current", ArgumentSemantic.Copy)]
    NSNumber Current { get; set; }

    // @property (copy, nonatomic) NSNumber * _Nullable isMain;
    [NullAllowed, Export("isMain", ArgumentSemantic.Copy)]
    NSNumber IsMain { get; set; }

    // -(instancetype _Nonnull)initWithThreadId:(NSNumber * _Nullable)threadId;
    [Export("initWithThreadId:")]
    NativeHandle Constructor([NullAllowed] NSNumber threadId);
}

// @interface SentryObjCUser : NSObject
[BaseType(typeof(NSObject))]
[Internal]
interface SentryObjCUser
{
    // @property (copy, nonatomic) NSString * _Nullable userId;
    [NullAllowed, Export("userId")]
    string UserId { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable email;
    [NullAllowed, Export("email")]
    string Email { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable username;
    [NullAllowed, Export("username")]
    string Username { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable ipAddress;
    [NullAllowed, Export("ipAddress")]
    string IpAddress { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable name;
    [NullAllowed, Export("name")]
    string Name { get; set; }

    // @property (nonatomic, strong) SentryObjCGeo * _Nullable geo;
    [NullAllowed, Export("geo", ArgumentSemantic.Strong)]
    SentryObjCGeo Geo { get; set; }

    // @property (nonatomic, strong) NSDictionary<NSString *,id> * _Nullable data;
    [NullAllowed, Export("data", ArgumentSemantic.Strong)]
    NSDictionary<NSString, NSObject> Data { get; set; }

    // -(instancetype _Nonnull)initWithUserId:(NSString * _Nonnull)userId;
    [Export("initWithUserId:")]
    NativeHandle Constructor(string userId);
}

// @interface SentryObjCSpanContext : NSObject
[BaseType(typeof(NSObject))]
[DisableDefaultCtor]
[Internal]
interface SentryObjCSpanContext
{
    // @property (readonly, nonatomic, strong) SentryObjCId * _Nonnull traceId;
    [Export("traceId", ArgumentSemantic.Strong)]
    SentryObjCId TraceId { get; }

    // @property (readonly, nonatomic, strong) SentryObjCSpanId * _Nonnull spanId;
    [Export("spanId", ArgumentSemantic.Strong)]
    SentryObjCSpanId SpanId { get; }

    // @property (readonly, nonatomic, strong) SentryObjCSpanId * _Nullable parentSpanId;
    [NullAllowed, Export("parentSpanId", ArgumentSemantic.Strong)]
    SentryObjCSpanId ParentSpanId { get; }

    // @property (readonly, nonatomic) SentryObjCSampleDecision sampled;
    [Export("sampled")]
    SentryObjCSampleDecision Sampled { get; }

    // @property (readonly, copy, nonatomic) NSString * _Nonnull operation;
    [Export("operation")]
    string Operation { get; }

    // @property (readonly, copy, nonatomic) NSString * _Nullable spanDescription;
    [NullAllowed, Export("spanDescription")]
    string SpanDescription { get; }

    // @property (copy, nonatomic) NSString * _Nonnull origin;
    [Export("origin")]
    string Origin { get; set; }

    // -(instancetype _Nonnull)initWithOperation:(NSString * _Nonnull)operation;
    [Export("initWithOperation:")]
    NativeHandle Constructor(string operation);

    // -(instancetype _Nonnull)initWithOperation:(NSString * _Nonnull)operation sampled:(SentryObjCSampleDecision)sampled;
    [Export("initWithOperation:sampled:")]
    NativeHandle Constructor(string operation, SentryObjCSampleDecision sampled);

    // -(instancetype _Nonnull)initWithTraceId:(SentryObjCId * _Nonnull)traceId spanId:(SentryObjCSpanId * _Nonnull)spanId parentId:(SentryObjCSpanId * _Nullable)parentId operation:(NSString * _Nonnull)operation sampled:(SentryObjCSampleDecision)sampled;
    [Export("initWithTraceId:spanId:parentId:operation:sampled:")]
    NativeHandle Constructor(SentryObjCId traceId, SentryObjCSpanId spanId, [NullAllowed] SentryObjCSpanId parentId, string operation, SentryObjCSampleDecision sampled);

    // -(instancetype _Nonnull)initWithTraceId:(SentryObjCId * _Nonnull)traceId spanId:(SentryObjCSpanId * _Nonnull)spanId parentId:(SentryObjCSpanId * _Nullable)parentId operation:(NSString * _Nonnull)operation spanDescription:(NSString * _Nullable)description sampled:(SentryObjCSampleDecision)sampled;
    [Export("initWithTraceId:spanId:parentId:operation:spanDescription:sampled:")]
    NativeHandle Constructor(SentryObjCId traceId, SentryObjCSpanId spanId, [NullAllowed] SentryObjCSpanId parentId, string operation, [NullAllowed] string description, SentryObjCSampleDecision sampled);
}

// @interface SentryObjCTransactionContext : SentryObjCSpanContext
[BaseType(typeof(SentryObjCSpanContext))]
[Internal]
interface SentryObjCTransactionContext
{
    // @property (readonly, copy, nonatomic) NSString * _Nonnull name;
    [Export("name")]
    string Name { get; }

    // @property (readonly, nonatomic) SentryObjCTransactionNameSource nameSource;
    [Export("nameSource")]
    SentryObjCTransactionNameSource NameSource { get; }

    // @property (nonatomic, strong) NSNumber * _Nullable sampleRate;
    [NullAllowed, Export("sampleRate", ArgumentSemantic.Strong)]
    NSNumber SampleRate { get; set; }

    // @property (nonatomic, strong) NSNumber * _Nullable sampleRand;
    [NullAllowed, Export("sampleRand", ArgumentSemantic.Strong)]
    NSNumber SampleRand { get; set; }

    // @property (nonatomic) SentryObjCSampleDecision parentSampled;
    [Export("parentSampled", ArgumentSemantic.Assign)]
    SentryObjCSampleDecision ParentSampled { get; set; }

    // @property (nonatomic, strong) NSNumber * _Nullable parentSampleRate;
    [NullAllowed, Export("parentSampleRate", ArgumentSemantic.Strong)]
    NSNumber ParentSampleRate { get; set; }

    // @property (nonatomic, strong) NSNumber * _Nullable parentSampleRand;
    [NullAllowed, Export("parentSampleRand", ArgumentSemantic.Strong)]
    NSNumber ParentSampleRand { get; set; }

    // @property (assign, nonatomic) BOOL forNextAppLaunch;
    [Export("forNextAppLaunch")]
    bool ForNextAppLaunch { get; set; }

    // -(instancetype _Nonnull)initWithName:(NSString * _Nonnull)name operation:(NSString * _Nonnull)operation;
    [Export("initWithName:operation:")]
    NativeHandle Constructor(string name, string operation);

    // -(instancetype _Nonnull)initWithName:(NSString * _Nonnull)name operation:(NSString * _Nonnull)operation sampled:(SentryObjCSampleDecision)sampled sampleRate:(NSNumber * _Nullable)sampleRate sampleRand:(NSNumber * _Nullable)sampleRand;
    [Export("initWithName:operation:sampled:sampleRate:sampleRand:")]
    NativeHandle Constructor(string name, string operation, SentryObjCSampleDecision sampled, [NullAllowed] NSNumber sampleRate, [NullAllowed] NSNumber sampleRand);

    // -(instancetype _Nonnull)initWithName:(NSString * _Nonnull)name operation:(NSString * _Nonnull)operation traceId:(SentryObjCId * _Nonnull)traceId spanId:(SentryObjCSpanId * _Nonnull)spanId parentSpanId:(SentryObjCSpanId * _Nullable)parentSpanId parentSampled:(SentryObjCSampleDecision)parentSampled parentSampleRate:(NSNumber * _Nullable)parentSampleRate parentSampleRand:(NSNumber * _Nullable)parentSampleRand;
    [Export("initWithName:operation:traceId:spanId:parentSpanId:parentSampled:parentSampleRate:parentSampleRand:")]
    NativeHandle Constructor(string name, string operation, SentryObjCId traceId, SentryObjCSpanId spanId, [NullAllowed] SentryObjCSpanId parentSpanId, SentryObjCSampleDecision parentSampled, [NullAllowed] NSNumber parentSampleRate, [NullAllowed] NSNumber parentSampleRand);
}

// @interface SentryObjCEvent : NSObject
[BaseType(typeof(NSObject))]
[Internal]
interface SentryObjCEvent
{
    // @property (nonatomic, strong) SentryObjCId * _Nonnull eventId;
    [Export("eventId", ArgumentSemantic.Strong)]
    SentryObjCId EventId { get; set; }

    // @property (nonatomic, strong) SentryObjCMessage * _Nullable message;
    [NullAllowed, Export("message", ArgumentSemantic.Strong)]
    SentryObjCMessage Message { get; set; }

    // @property (copy, nonatomic) NSError * _Nullable error;
    [NullAllowed, Export("error", ArgumentSemantic.Copy)]
    NSError Error { get; set; }

    // @property (nonatomic, strong) NSDate * _Nullable timestamp;
    [NullAllowed, Export("timestamp", ArgumentSemantic.Strong)]
    NSDate Timestamp { get; set; }

    // @property (nonatomic, strong) NSDate * _Nullable startTimestamp;
    [NullAllowed, Export("startTimestamp", ArgumentSemantic.Strong)]
    NSDate StartTimestamp { get; set; }

    // @property (nonatomic) SentryObjCLevel level;
    [Export("level", ArgumentSemantic.Assign)]
    SentryObjCLevel Level { get; set; }

    // @property (copy, nonatomic) NSString * _Nonnull platform;
    [Export("platform")]
    string Platform { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable logger;
    [NullAllowed, Export("logger")]
    string Logger { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable serverName;
    [NullAllowed, Export("serverName")]
    string ServerName { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable releaseName;
    [NullAllowed, Export("releaseName")]
    string ReleaseName { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable dist;
    [NullAllowed, Export("dist")]
    string Dist { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable environment;
    [NullAllowed, Export("environment")]
    string Environment { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable transaction;
    [NullAllowed, Export("transaction")]
    string Transaction { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable type;
    [NullAllowed, Export("type")]
    string Type { get; set; }

    // @property (nonatomic, strong) NSDictionary<NSString *,NSString *> * _Nullable tags;
    [NullAllowed, Export("tags", ArgumentSemantic.Strong)]
    NSDictionary<NSString, NSString> Tags { get; set; }

    // @property (nonatomic, strong) NSDictionary<NSString *,id> * _Nullable extra;
    [NullAllowed, Export("extra", ArgumentSemantic.Strong)]
    NSDictionary<NSString, NSObject> Extra { get; set; }

    // @property (nonatomic, strong) NSDictionary<NSString *,id> * _Nullable sdk;
    [NullAllowed, Export("sdk", ArgumentSemantic.Strong)]
    NSDictionary<NSString, NSObject> Sdk { get; set; }

    // @property (nonatomic, strong) NSDictionary<NSString *,NSString *> * _Nullable modules;
    [NullAllowed, Export("modules", ArgumentSemantic.Strong)]
    NSDictionary<NSString, NSString> Modules { get; set; }

    // @property (nonatomic, strong) NSArray<NSString *> * _Nullable fingerprint;
    [NullAllowed, Export("fingerprint", ArgumentSemantic.Strong)]
    string[] Fingerprint { get; set; }

    // @property (nonatomic, strong) SentryObjCUser * _Nullable user;
    [NullAllowed, Export("user", ArgumentSemantic.Strong)]
    SentryObjCUser User { get; set; }

    // @property (nonatomic, strong) NSDictionary<NSString *,NSDictionary<NSString *,id> *> * _Nullable context;
    [NullAllowed, Export("context", ArgumentSemantic.Strong)]
    NSDictionary<NSString, NSDictionary<NSString, NSObject>> Context { get; set; }

    // @property (nonatomic, strong) NSArray<SentryObjCThread *> * _Nullable threads;
    [NullAllowed, Export("threads", ArgumentSemantic.Strong)]
    SentryObjCThread[] Threads { get; set; }

    // @property (nonatomic, strong) NSArray<SentryObjCException *> * _Nullable exceptions;
    [NullAllowed, Export("exceptions", ArgumentSemantic.Strong)]
    SentryObjCException[] Exceptions { get; set; }

    // @property (nonatomic, strong) SentryObjCStacktrace * _Nullable stacktrace;
    [NullAllowed, Export("stacktrace", ArgumentSemantic.Strong)]
    SentryObjCStacktrace Stacktrace { get; set; }

    // @property (nonatomic, strong) NSArray<SentryObjCDebugMeta *> * _Nullable debugMeta;
    [NullAllowed, Export("debugMeta", ArgumentSemantic.Strong)]
    SentryObjCDebugMeta[] DebugMeta { get; set; }

    // @property (nonatomic, strong) NSArray<SentryObjCBreadcrumb *> * _Nullable breadcrumbs;
    [NullAllowed, Export("breadcrumbs", ArgumentSemantic.Strong)]
    SentryObjCBreadcrumb[] Breadcrumbs { get; set; }

    // @property (nonatomic, strong) SentryObjCRequest * _Nullable request;
    [NullAllowed, Export("request", ArgumentSemantic.Strong)]
    SentryObjCRequest Request { get; set; }

    // -(instancetype _Nonnull)initWithLevel:(SentryObjCLevel)level;
    [Export("initWithLevel:")]
    NativeHandle Constructor(SentryObjCLevel level);

    // -(instancetype _Nonnull)initWithError:(NSError * _Nonnull)error;
    [Export("initWithError:")]
    NativeHandle Constructor(NSError error);
}

// @interface SentryObjCSamplingContext : NSObject
[BaseType(typeof(NSObject))]
[DisableDefaultCtor]
[Internal]
interface SentryObjCSamplingContext
{
    // @property (readonly, nonatomic, strong) SentryObjCTransactionContext * _Nonnull transactionContext;
    [Export("transactionContext", ArgumentSemantic.Strong)]
    SentryObjCTransactionContext TransactionContext { get; }

    // @property (readonly, nonatomic, strong) NSDictionary<NSString *,id> * _Nullable customSamplingContext;
    [NullAllowed, Export("customSamplingContext", ArgumentSemantic.Strong)]
    NSDictionary<NSString, NSObject> CustomSamplingContext { get; }

    // -(instancetype _Nonnull)initWithTransactionContext:(SentryObjCTransactionContext * _Nonnull)transactionContext;
    [Export("initWithTransactionContext:")]
    NativeHandle Constructor(SentryObjCTransactionContext transactionContext);

    // -(instancetype _Nonnull)initWithTransactionContext:(SentryObjCTransactionContext * _Nonnull)transactionContext customSamplingContext:(NSDictionary<NSString *,id> * _Nonnull)customSamplingContext;
    [Export("initWithTransactionContext:customSamplingContext:")]
    NativeHandle Constructor(SentryObjCTransactionContext transactionContext, NSDictionary<NSString, NSObject> customSamplingContext);
}

// @interface SentryObjCScope : NSObject
[BaseType(typeof(NSObject))]
[Internal]
interface SentryObjCScope
{
    // @property (copy, nonatomic) NSString * _Nullable replayId;
    [NullAllowed, Export("replayId")]
    string ReplayId { get; set; }

    // @property (readonly, copy, nonatomic) NSDictionary<NSString *,NSString *> * _Nonnull tags;
    [Export("tags", ArgumentSemantic.Copy)]
    NSDictionary<NSString, NSString> Tags { get; }

    // @property (readonly, copy, nonatomic) NSDictionary<NSString *,id> * _Nonnull attributes;
    [Export("attributes", ArgumentSemantic.Copy)]
    NSDictionary<NSString, NSObject> Attributes { get; }

    // -(instancetype _Nonnull)initWithMaxBreadcrumbs:(NSInteger)maxBreadcrumbs;
    [Export("initWithMaxBreadcrumbs:")]
    NativeHandle Constructor(nint maxBreadcrumbs);

    // -(void)setUser:(SentryObjCUser * _Nullable)user;
    [Export("setUser:")]
    void SetUser([NullAllowed] SentryObjCUser user);

    // -(void)setTagValue:(NSString * _Nonnull)value forKey:(NSString * _Nonnull)key;
    [Export("setTagValue:forKey:")]
    void SetTagValue(string value, string key);

    // -(void)removeTagForKey:(NSString * _Nonnull)key;
    [Export("removeTagForKey:")]
    void RemoveTagForKey(string key);

    // -(void)setTags:(NSDictionary<NSString *,NSString *> * _Nullable)tags;
    [Export("setTags:")]
    void SetTags([NullAllowed] NSDictionary<NSString, NSString> tags);

    // -(void)setExtras:(NSDictionary<NSString *,id> * _Nullable)extras;
    [Export("setExtras:")]
    void SetExtras([NullAllowed] NSDictionary<NSString, NSObject> extras);

    // -(void)setExtraValue:(id _Nullable)value forKey:(NSString * _Nonnull)key;
    [Export("setExtraValue:forKey:")]
    void SetExtraValue([NullAllowed] NSObject value, string key);

    // -(void)removeExtraForKey:(NSString * _Nonnull)key;
    [Export("removeExtraForKey:")]
    void RemoveExtraForKey(string key);

    // -(void)setDist:(NSString * _Nullable)dist;
    [Export("setDist:")]
    void SetDist([NullAllowed] string dist);

    // -(void)setEnvironment:(NSString * _Nullable)environment;
    [Export("setEnvironment:")]
    void SetEnvironment([NullAllowed] string environment);

    // -(void)setFingerprint:(NSArray<NSString *> * _Nullable)fingerprint;
    [Export("setFingerprint:")]
    void SetFingerprint([NullAllowed] string[] fingerprint);

    // -(void)setLevel:(SentryObjCLevel)level;
    [Export("setLevel:")]
    void SetLevel(SentryObjCLevel level);

    // -(void)addBreadcrumb:(SentryObjCBreadcrumb * _Nonnull)crumb;
    [Export("addBreadcrumb:")]
    void AddBreadcrumb(SentryObjCBreadcrumb crumb);

    // -(void)clearBreadcrumbs;
    [Export("clearBreadcrumbs")]
    void ClearBreadcrumbs();

    // -(void)addFeatureFlagWithName:(NSString * _Nonnull)name result:(BOOL)result;
    [Export("addFeatureFlagWithName:result:")]
    void AddFeatureFlagWithName(string name, bool result);

    // -(void)clearFeatureFlags;
    [Export("clearFeatureFlags")]
    void ClearFeatureFlags();

    // -(void)setContextValue:(NSDictionary<NSString *,id> * _Nonnull)value forKey:(NSString * _Nonnull)key;
    [Export("setContextValue:forKey:")]
    void SetContextValue(NSDictionary<NSString, NSObject> value, string key);

    // -(void)removeContextForKey:(NSString * _Nonnull)key;
    [Export("removeContextForKey:")]
    void RemoveContextForKey(string key);

    // -(void)addAttachment:(SentryObjCAttachment * _Nonnull)attachment;
    [Export("addAttachment:")]
    void AddAttachment(SentryObjCAttachment attachment);

    // -(void)setAttributeValue:(id _Nonnull)value forKey:(NSString * _Nonnull)key;
    [Export("setAttributeValue:forKey:")]
    void SetAttributeValue(NSObject value, string key);

    // -(void)removeAttributeForKey:(NSString * _Nonnull)key;
    [Export("removeAttributeForKey:")]
    void RemoveAttributeForKey(string key);

    // -(void)clearAttachments;
    [Export("clearAttachments")]
    void ClearAttachments();

    // @property (nonatomic, strong) SentryObjCSpan * _Nullable span;
    [NullAllowed, Export("span", ArgumentSemantic.Strong)]
    SentryObjCSpan Span { get; set; }

    // -(NSDictionary<NSString *,id> * _Nonnull)serialize;
    [Export("serialize")]
    NSDictionary<NSString, NSObject> Serialize();

    // -(void)clear;
    [Export("clear")]
    void Clear();
}

// @interface SentryObjCSpan : NSObject
[BaseType(typeof(NSObject))]
[DisableDefaultCtor]
[Internal]
interface SentryObjCSpan
{
    // @property (nonatomic, strong) SentryObjCId * _Nonnull traceId;
    [Export("traceId", ArgumentSemantic.Strong)]
    SentryObjCId TraceId { get; set; }

    // @property (nonatomic, strong) SentryObjCSpanId * _Nonnull spanId;
    [Export("spanId", ArgumentSemantic.Strong)]
    SentryObjCSpanId SpanId { get; set; }

    // @property (nonatomic, strong) SentryObjCSpanId * _Nullable parentSpanId;
    [NullAllowed, Export("parentSpanId", ArgumentSemantic.Strong)]
    SentryObjCSpanId ParentSpanId { get; set; }

    // @property (nonatomic) SentryObjCSampleDecision sampled;
    [Export("sampled", ArgumentSemantic.Assign)]
    SentryObjCSampleDecision Sampled { get; set; }

    // @property (copy, nonatomic) NSString * _Nonnull operation;
    [Export("operation")]
    string Operation { get; set; }

    // @property (copy, nonatomic) NSString * _Nonnull origin;
    [Export("origin")]
    string Origin { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable spanDescription;
    [NullAllowed, Export("spanDescription")]
    string SpanDescription { get; set; }

    // @property (nonatomic) SentryObjCSpanStatus status;
    [Export("status", ArgumentSemantic.Assign)]
    SentryObjCSpanStatus Status { get; set; }

    // @property (nonatomic, strong) NSDate * _Nullable timestamp;
    [NullAllowed, Export("timestamp", ArgumentSemantic.Strong)]
    NSDate Timestamp { get; set; }

    // @property (nonatomic, strong) NSDate * _Nullable startTimestamp;
    [NullAllowed, Export("startTimestamp", ArgumentSemantic.Strong)]
    NSDate StartTimestamp { get; set; }

    // @property (readonly, copy, nonatomic) NSDictionary<NSString *,id> * _Nonnull data;
    [Export("data", ArgumentSemantic.Copy)]
    NSDictionary<NSString, NSObject> Data { get; }

    // @property (readonly, copy, nonatomic) NSDictionary<NSString *,NSString *> * _Nonnull tags;
    [Export("tags", ArgumentSemantic.Copy)]
    NSDictionary<NSString, NSString> Tags { get; }

    // @property (readonly, nonatomic) BOOL isFinished;
    [Export("isFinished")]
    bool IsFinished { get; }

    // @property (readonly, nonatomic, strong) SentryObjCTraceContext * _Nullable traceContext;
    [NullAllowed, Export("traceContext", ArgumentSemantic.Strong)]
    SentryObjCTraceContext TraceContext { get; }

    // -(SentryObjCSpan * _Nonnull)startChildWithOperation:(NSString * _Nonnull)operation;
    [Export("startChildWithOperation:")]
    SentryObjCSpan StartChildWithOperation(string operation);

    // -(SentryObjCSpan * _Nonnull)startChildWithOperation:(NSString * _Nonnull)operation description:(NSString * _Nullable)description;
    [Export("startChildWithOperation:description:")]
    SentryObjCSpan StartChildWithOperation(string operation, [NullAllowed] string description);

    // -(void)setDataValue:(id _Nullable)value forKey:(NSString * _Nonnull)key;
    [Export("setDataValue:forKey:")]
    void SetDataValue([NullAllowed] NSObject value, string key);

    // -(void)removeDataForKey:(NSString * _Nonnull)key;
    [Export("removeDataForKey:")]
    void RemoveDataForKey(string key);

    // -(void)setTagValue:(NSString * _Nonnull)value forKey:(NSString * _Nonnull)key;
    [Export("setTagValue:forKey:")]
    void SetTagValue(string value, string key);

    // -(void)removeTagForKey:(NSString * _Nonnull)key;
    [Export("removeTagForKey:")]
    void RemoveTagForKey(string key);

    // -(void)setMeasurementWithName:(NSString * _Nonnull)name value:(NSNumber * _Nonnull)value;
    [Export("setMeasurementWithName:value:")]
    void SetMeasurementWithName(string name, NSNumber value);

    // -(void)setMeasurementWithName:(NSString * _Nonnull)name value:(NSNumber * _Nonnull)value unit:(SentryObjCMeasurementUnit * _Nonnull)unit;
    [Export("setMeasurementWithName:value:unit:")]
    void SetMeasurementWithName(string name, NSNumber value, SentryObjCMeasurementUnit unit);

    // -(void)finish;
    [Export("finish")]
    void Finish();

    // -(void)finishWithStatus:(SentryObjCSpanStatus)status;
    [Export("finishWithStatus:")]
    void FinishWithStatus(SentryObjCSpanStatus status);

    // -(SentryObjCTraceHeader * _Nonnull)toTraceHeader;
    [Export("toTraceHeader")]
    SentryObjCTraceHeader ToTraceHeader();

    // -(NSString * _Nullable)baggageHttpHeader;
    [NullAllowed, Export("baggageHttpHeader")]
    string BaggageHttpHeader { get; }
}

// @interface SentryObjCTraceContext : NSObject
[BaseType(typeof(NSObject))]
[DisableDefaultCtor]
[Internal]
interface SentryObjCTraceContext
{
    // @property (readonly, nonatomic, strong) SentryObjCId * _Nonnull traceId;
    [Export("traceId", ArgumentSemantic.Strong)]
    SentryObjCId TraceId { get; }

    // @property (readonly, copy, nonatomic) NSString * _Nonnull publicKey;
    [Export("publicKey")]
    string PublicKey { get; }

    // @property (readonly, copy, nonatomic) NSString * _Nullable releaseName;
    [NullAllowed, Export("releaseName")]
    string ReleaseName { get; }

    // @property (readonly, copy, nonatomic) NSString * _Nullable environment;
    [NullAllowed, Export("environment")]
    string Environment { get; }

    // @property (readonly, copy, nonatomic) NSString * _Nullable transaction;
    [NullAllowed, Export("transaction")]
    string Transaction { get; }

    // @property (readonly, copy, nonatomic) NSString * _Nullable sampleRate;
    [NullAllowed, Export("sampleRate")]
    string SampleRate { get; }

    // @property (readonly, copy, nonatomic) NSString * _Nullable sampleRand;
    [NullAllowed, Export("sampleRand")]
    string SampleRand { get; }

    // @property (readonly, copy, nonatomic) NSString * _Nullable sampled;
    [NullAllowed, Export("sampled")]
    string Sampled { get; }

    // @property (readonly, copy, nonatomic) NSString * _Nullable replayId;
    [NullAllowed, Export("replayId")]
    string ReplayId { get; }

    // @property (readonly, copy, nonatomic) NSString * _Nullable orgId;
    [NullAllowed, Export("orgId")]
    string OrgId { get; }

    // -(instancetype _Nullable)initWithTestDict:(NSDictionary<NSString *,id> * _Nonnull)dict;
    [Export("initWithTestDict:")]
    NativeHandle Constructor(NSDictionary<NSString, NSObject> dict);
}

// @interface SentryObjCExperimentalOptions : NSObject
[BaseType(typeof(NSObject))]
[Internal]
interface SentryObjCExperimentalOptions
{
    // @property (nonatomic) BOOL enableUnhandledCPPExceptionsV2;
    [Export("enableUnhandledCPPExceptionsV2")]
    bool EnableUnhandledCPPExceptionsV2 { get; set; }

    // @property (nonatomic) BOOL enableWatchdogTerminationsV2;
    [Export("enableWatchdogTerminationsV2")]
    bool EnableWatchdogTerminationsV2 { get; set; }
}

// @interface SentryObjCOptions : NSObject
[BaseType(typeof(NSObject))]
[Internal]
interface SentryObjCOptions
{
    // @property (copy, nonatomic) NSString * _Nullable dsn;
    [NullAllowed, Export("dsn")]
    string Dsn { get; set; }

    // @property (nonatomic) BOOL debug;
    [Export("debug")]
    bool Debug { get; set; }

    // @property (nonatomic) SentryObjCLevel diagnosticLevel;
    [Export("diagnosticLevel", ArgumentSemantic.Assign)]
    SentryObjCLevel DiagnosticLevel { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable releaseName;
    [NullAllowed, Export("releaseName")]
    string ReleaseName { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable dist;
    [NullAllowed, Export("dist")]
    string Dist { get; set; }

    // @property (copy, nonatomic) NSString * _Nonnull environment;
    [Export("environment")]
    string Environment { get; set; }

    // @property (nonatomic) BOOL enabled;
    [Export("enabled")]
    bool Enabled { get; set; }

    // @property (nonatomic) NSTimeInterval shutdownTimeInterval;
    [Export("shutdownTimeInterval")]
    double ShutdownTimeInterval { get; set; }

    // @property (nonatomic) BOOL enableCrashHandler;
    [Export("enableCrashHandler")]
    bool EnableCrashHandler { get; set; }

    // @property (nonatomic) NSUInteger maxBreadcrumbs;
    [Export("maxBreadcrumbs")]
    nuint MaxBreadcrumbs { get; set; }

    // @property (nonatomic) BOOL enableNetworkBreadcrumbs;
    [Export("enableNetworkBreadcrumbs")]
    bool EnableNetworkBreadcrumbs { get; set; }

    // @property (nonatomic) NSUInteger maxCacheItems;
    [Export("maxCacheItems")]
    nuint MaxCacheItems { get; set; }

    // @property (copy, nonatomic) SentryObjCEvent * _Nullable (^ _Nullable)(SentryObjCEvent * _Nonnull) beforeSend;
    [NullAllowed, Export("beforeSend", ArgumentSemantic.Copy)]
    Func<SentryObjCEvent, SentryObjCEvent> BeforeSend { get; set; }

    // @property (copy, nonatomic) SentryObjCSpan * _Nullable (^ _Nullable)(SentryObjCSpan * _Nonnull) beforeSendSpan;
    [NullAllowed, Export("beforeSendSpan", ArgumentSemantic.Copy)]
    Func<SentryObjCSpan, SentryObjCSpan> BeforeSendSpan { get; set; }

    // @property (nonatomic) BOOL enableLogs;
    [Export("enableLogs")]
    bool EnableLogs { get; set; }

    // @property (copy, nonatomic) SentryObjCBreadcrumb * _Nullable (^ _Nullable)(SentryObjCBreadcrumb * _Nonnull) beforeBreadcrumb;
    [NullAllowed, Export("beforeBreadcrumb", ArgumentSemantic.Copy)]
    Func<SentryObjCBreadcrumb, SentryObjCBreadcrumb> BeforeBreadcrumb { get; set; }

    // @property (copy, nonatomic) BOOL (^ _Nullable)(SentryObjCEvent * _Nonnull) beforeCaptureScreenshot;
    [NullAllowed, Export("beforeCaptureScreenshot", ArgumentSemantic.Copy)]
    Func<SentryObjCEvent, bool> BeforeCaptureScreenshot { get; set; }

    // @property (copy, nonatomic) BOOL (^ _Nullable)(SentryObjCEvent * _Nonnull) beforeCaptureViewHierarchy;
    [NullAllowed, Export("beforeCaptureViewHierarchy", ArgumentSemantic.Copy)]
    Func<SentryObjCEvent, bool> BeforeCaptureViewHierarchy { get; set; }

    // @property (copy, nonatomic) void (^ _Nullable)(SentryObjCEvent * _Nonnull) onCrashedLastRun __attribute__((deprecated("Use onLastRunStatusDetermined instead.")));
    [NullAllowed, Export("onCrashedLastRun", ArgumentSemantic.Copy)]
    Action<SentryObjCEvent> OnCrashedLastRun { get; set; }

    // @property (copy, nonatomic) void (^ _Nullable)(SentryObjCLastRunStatus, SentryObjCEvent * _Nullable) onLastRunStatusDetermined;
    [NullAllowed, Export("onLastRunStatusDetermined", ArgumentSemantic.Copy)]
    Action<SentryObjCLastRunStatus, SentryObjCEvent?> OnLastRunStatusDetermined { get; set; }

    // @property (nonatomic, strong) NSNumber * _Nullable sampleRate;
    [NullAllowed, Export("sampleRate", ArgumentSemantic.Strong)]
    NSNumber SampleRate { get; set; }

    // @property (nonatomic) BOOL enableAutoSessionTracking;
    [Export("enableAutoSessionTracking")]
    bool EnableAutoSessionTracking { get; set; }

    // @property (nonatomic) BOOL enableGraphQLOperationTracking;
    [Export("enableGraphQLOperationTracking")]
    bool EnableGraphQLOperationTracking { get; set; }

    // @property (nonatomic) BOOL enableWatchdogTerminationTracking;
    [Export("enableWatchdogTerminationTracking")]
    bool EnableWatchdogTerminationTracking { get; set; }

    // @property (nonatomic) NSUInteger sessionTrackingIntervalMillis;
    [Export("sessionTrackingIntervalMillis")]
    nuint SessionTrackingIntervalMillis { get; set; }

    // @property (nonatomic) BOOL attachStacktrace;
    [Export("attachStacktrace")]
    bool AttachStacktrace { get; set; }

    // @property (nonatomic) BOOL attachAllThreads;
    [Export("attachAllThreads")]
    bool AttachAllThreads { get; set; }

    // @property (nonatomic) NSUInteger maxAttachmentSize;
    [Export("maxAttachmentSize")]
    nuint MaxAttachmentSize { get; set; }

    // @property (nonatomic) BOOL sendDefaultPii;
    [Export("sendDefaultPii")]
    bool SendDefaultPii { get; set; }

    // @property (nonatomic) BOOL enableAutoPerformanceTracing;
    [Export("enableAutoPerformanceTracing")]
    bool EnableAutoPerformanceTracing { get; set; }

    // @property (nonatomic) BOOL enablePersistingTracesWhenCrashing;
    [Export("enablePersistingTracesWhenCrashing")]
    bool EnablePersistingTracesWhenCrashing { get; set; }

    // @property (copy, nonatomic) SentryObjCScope * _Nonnull (^ _Nonnull)(SentryObjCScope * _Nonnull) initialScope;
    [Export("initialScope", ArgumentSemantic.Copy)]
    Func<SentryObjCScope, SentryObjCScope> InitialScope { get; set; }

    // @property (nonatomic) BOOL enableNetworkTracking;
    [Export("enableNetworkTracking")]
    bool EnableNetworkTracking { get; set; }

    // @property (nonatomic) BOOL enableFileIOTracing;
    [Export("enableFileIOTracing")]
    bool EnableFileIOTracing { get; set; }

    // @property (nonatomic) BOOL enableDataSwizzling;
    [Export("enableDataSwizzling")]
    bool EnableDataSwizzling { get; set; }

    // @property (nonatomic) BOOL enableFileManagerSwizzling;
    [Export("enableFileManagerSwizzling")]
    bool EnableFileManagerSwizzling { get; set; }

    // @property (nonatomic, strong) NSNumber * _Nullable tracesSampleRate;
    [NullAllowed, Export("tracesSampleRate", ArgumentSemantic.Strong)]
    NSNumber TracesSampleRate { get; set; }

    // @property (copy, nonatomic) NSNumber * _Nullable (^ _Nullable)(SentryObjCSamplingContext * _Nonnull) tracesSampler;
    [NullAllowed, Export("tracesSampler", ArgumentSemantic.Copy)]
    Func<SentryObjCSamplingContext, NSNumber> TracesSampler { get; set; }

    // @property (readonly, nonatomic) BOOL isTracingEnabled;
    [Export("isTracingEnabled")]
    bool IsTracingEnabled { get; }

    // @property (readonly, copy, nonatomic) NSArray<NSString *> * _Nonnull inAppIncludes;
    [Export("inAppIncludes", ArgumentSemantic.Copy)]
    string[] InAppIncludes { get; }

    [Wrap("WeakUrlSessionDelegate")]
    [NullAllowed]
    NSUrlSessionDelegate UrlSessionDelegate { get; set; }

    // @property (nonatomic, weak) id<NSURLSessionDelegate> _Nullable urlSessionDelegate;
    [NullAllowed, Export("urlSessionDelegate", ArgumentSemantic.Weak)]
    NSObject WeakUrlSessionDelegate { get; set; }

    // @property (nonatomic, strong) NSURLSession * _Nullable urlSession;
    [NullAllowed, Export("urlSession", ArgumentSemantic.Strong)]
    NSUrlSession UrlSession { get; set; }

    // @property (nonatomic) BOOL enableSwizzling;
    [Export("enableSwizzling")]
    bool EnableSwizzling { get; set; }

    // @property (copy, nonatomic) NSSet<NSString *> * _Nonnull swizzleClassNameExcludes;
    [Export("swizzleClassNameExcludes", ArgumentSemantic.Copy)]
    NSSet<NSString> SwizzleClassNameExcludes { get; set; }

    // @property (nonatomic) BOOL enableCoreDataTracing;
    [Export("enableCoreDataTracing")]
    bool EnableCoreDataTracing { get; set; }

    // @property (nonatomic) BOOL sendClientReports;
    [Export("sendClientReports")]
    bool SendClientReports { get; set; }

    // @property (nonatomic) BOOL enableAppHangTracking;
    [Export("enableAppHangTracking")]
    bool EnableAppHangTracking { get; set; }

    // @property (nonatomic) NSTimeInterval appHangTimeoutInterval;
    [Export("appHangTimeoutInterval")]
    double AppHangTimeoutInterval { get; set; }

    // @property (nonatomic) BOOL enableAutoBreadcrumbTracking;
    [Export("enableAutoBreadcrumbTracking")]
    bool EnableAutoBreadcrumbTracking { get; set; }

    // @property (nonatomic) BOOL enablePropagateTraceparent;
    [Export("enablePropagateTraceparent")]
    bool EnablePropagateTraceparent { get; set; }

    // @property (copy, nonatomic) NSArray * _Nonnull tracePropagationTargets;
    [Export("tracePropagationTargets", ArgumentSemantic.Copy)]
    NSObject[] TracePropagationTargets { get; set; }

    // @property (nonatomic) BOOL enableCaptureFailedRequests;
    [Export("enableCaptureFailedRequests")]
    bool EnableCaptureFailedRequests { get; set; }

    // @property (copy, nonatomic) NSArray<SentryObjCHttpStatusCodeRange *> * _Nonnull failedRequestStatusCodes;
    [Export("failedRequestStatusCodes", ArgumentSemantic.Copy)]
    SentryObjCHttpStatusCodeRange[] FailedRequestStatusCodes { get; set; }

    // @property (copy, nonatomic) NSArray * _Nonnull failedRequestTargets;
    [Export("failedRequestTargets", ArgumentSemantic.Copy)]
    NSObject[] FailedRequestTargets { get; set; }

    // @property (nonatomic) BOOL enableTimeToFullDisplayTracing;
    [Export("enableTimeToFullDisplayTracing")]
    bool EnableTimeToFullDisplayTracing { get; set; }

    // @property (nonatomic) BOOL swiftAsyncStacktraces;
    [Export("swiftAsyncStacktraces")]
    bool SwiftAsyncStacktraces { get; set; }

    // @property (copy, nonatomic) NSString * _Nonnull cacheDirectoryPath;
    [Export("cacheDirectoryPath")]
    string CacheDirectoryPath { get; set; }

    // @property (nonatomic) BOOL enableSpotlight;
    [Export("enableSpotlight")]
    bool EnableSpotlight { get; set; }

    // @property (copy, nonatomic) NSString * _Nonnull spotlightUrl;
    [Export("spotlightUrl")]
    string SpotlightUrl { get; set; }

    // @property (nonatomic) BOOL strictTraceContinuation;
    [Export("strictTraceContinuation")]
    bool StrictTraceContinuation { get; set; }

    // @property (copy, nonatomic) NSString * _Nullable orgId;
    [NullAllowed, Export("orgId")]
    string OrgId { get; set; }

    // @property (nonatomic, strong) SentryObjCExperimentalOptions * _Nonnull experimental;
    [Export("experimental", ArgumentSemantic.Strong)]
    SentryObjCExperimentalOptions Experimental { get; set; }

    // @property (nonatomic) BOOL enableMetrics;
    [Export("enableMetrics")]
    bool EnableMetrics { get; set; }

    // @property (nonatomic) BOOL enableUIViewControllerTracing;
    [Export("enableUIViewControllerTracing")]
    bool EnableUIViewControllerTracing { get; set; }

    // @property (nonatomic) BOOL attachScreenshot;
    [Export("attachScreenshot")]
    bool AttachScreenshot { get; set; }

    // @property (nonatomic) BOOL attachViewHierarchy;
    [Export("attachViewHierarchy")]
    bool AttachViewHierarchy { get; set; }

    // @property (nonatomic) BOOL reportAccessibilityIdentifier;
    [Export("reportAccessibilityIdentifier")]
    bool ReportAccessibilityIdentifier { get; set; }

    // @property (nonatomic) BOOL enableUserInteractionTracing;
    [Export("enableUserInteractionTracing")]
    bool EnableUserInteractionTracing { get; set; }

    // @property (nonatomic) NSTimeInterval idleTimeout;
    [Export("idleTimeout")]
    double IdleTimeout { get; set; }

    // @property (nonatomic) BOOL enablePreWarmedAppStartTracing;
    [Export("enablePreWarmedAppStartTracing")]
    bool EnablePreWarmedAppStartTracing { get; set; }

    // @property (nonatomic) BOOL enableReportNonFullyBlockingAppHangs;
    [Export("enableReportNonFullyBlockingAppHangs")]
    bool EnableReportNonFullyBlockingAppHangs { get; set; }

    // @property (nonatomic, strong) SentryObjCReplayOptions * _Nonnull sessionReplay;
    [Export("sessionReplay", ArgumentSemantic.Strong)]
    SentryObjCReplayOptions SessionReplay { get; set; }

    // @property (nonatomic) BOOL enableSigtermReporting;
    [Export("enableSigtermReporting")]
    bool EnableSigtermReporting { get; set; }

    // @property (nonatomic) BOOL enableMetricKit;
    [Export("enableMetricKit")]
    bool EnableMetricKit { get; set; }

    // @property (nonatomic) BOOL enableMetricKitRawPayload;
    [Export("enableMetricKitRawPayload")]
    bool EnableMetricKitRawPayload { get; set; }

    // -(void)addInAppInclude:(NSString * _Nonnull)inAppInclude;
    [Export("addInAppInclude:")]
    void AddInAppInclude(string inAppInclude);
}

// @interface SentryObjCReplayOptions : NSObject
[BaseType(typeof(NSObject))]
[Internal]
interface SentryObjCReplayOptions
{
    // @property (nonatomic) float sessionSampleRate;
    [Export("sessionSampleRate")]
    float SessionSampleRate { get; set; }

    // @property (nonatomic) float onErrorSampleRate;
    [Export("onErrorSampleRate")]
    float OnErrorSampleRate { get; set; }

    // @property (nonatomic) BOOL maskAllText;
    [Export("maskAllText")]
    bool MaskAllText { get; set; }

    // @property (nonatomic) BOOL maskAllImages;
    [Export("maskAllImages")]
    bool MaskAllImages { get; set; }

    // @property (nonatomic) SentryObjCReplayQuality quality;
    [Export("quality", ArgumentSemantic.Assign)]
    SentryObjCReplayQuality Quality { get; set; }

    // @property (nonatomic) BOOL enableViewRendererV2;
    [Export("enableViewRendererV2")]
    bool EnableViewRendererV2 { get; set; }

    // @property (nonatomic) BOOL enableFastViewRendering;
    [Export("enableFastViewRendering")]
    bool EnableFastViewRendering { get; set; }

    // @property (copy, nonatomic) NSArray<Class> * _Nonnull maskedViewClasses;
    [Export("maskedViewClasses", ArgumentSemantic.Copy)]
    Class[] MaskedViewClasses { get; set; }

    // @property (copy, nonatomic) NSArray<Class> * _Nonnull unmaskedViewClasses;
    [Export("unmaskedViewClasses", ArgumentSemantic.Copy)]
    Class[] UnmaskedViewClasses { get; set; }

    // @property (nonatomic) BOOL networkCaptureBodies;
    [Export("networkCaptureBodies")]
    bool NetworkCaptureBodies { get; set; }

    // @property (copy, nonatomic) NSArray<NSString *> * _Nonnull networkRequestHeaders;
    [Export("networkRequestHeaders", ArgumentSemantic.Copy)]
    string[] NetworkRequestHeaders { get; set; }

    // @property (copy, nonatomic) NSArray<NSString *> * _Nonnull networkResponseHeaders;
    [Export("networkResponseHeaders", ArgumentSemantic.Copy)]
    string[] NetworkResponseHeaders { get; set; }

    // -(void)excludeViewTypeFromSubtreeTraversal:(NSString * _Nonnull)viewType;
    [Export("excludeViewTypeFromSubtreeTraversal:")]
    void ExcludeViewTypeFromSubtreeTraversal(string viewType);

    // -(void)includeViewTypeInSubtreeTraversal:(NSString * _Nonnull)viewType;
    [Export("includeViewTypeInSubtreeTraversal:")]
    void IncludeViewTypeInSubtreeTraversal(string viewType);
}

// @interface SentryObjCInternalApi : NSObject
[BaseType(typeof(NSObject))]
[DisableDefaultCtor]
[Internal]
interface SentryObjCInternalApi
{
    // @property (readonly, nonatomic) SentryObjCInternalSdkApi * _Nonnull sdk;
    [Export("sdk")]
    SentryObjCInternalSdkApi Sdk { get; }

    // @property (readonly, nonatomic) SentryObjCInternalDebugApi * _Nonnull debug;
    [Export("debug")]
    SentryObjCInternalDebugApi Debug { get; }

    // @property (readonly, nonatomic) SentryObjCInternalProfilingApi * _Nonnull profiling;
    [Export("profiling")]
    SentryObjCInternalProfilingApi Profiling { get; }

    // -(void)setTrace:(SentryObjCId * _Nonnull)traceId spanId:(SentryObjCSpanId * _Nonnull)spanId;
    [Export("setTrace:spanId:")]
    void SetTrace(SentryObjCId traceId, SentryObjCSpanId spanId);

    // -(void)ignoreNextSignal:(int)signum;
    [Export("ignoreNextSignal:")]
    void IgnoreNextSignal(int signum);
}

// @interface SentryObjCInternalDebugApi : NSObject
[BaseType(typeof(NSObject))]
[Internal]
interface SentryObjCInternalDebugApi
{
    // @property (readonly, copy, nonatomic) NSArray<SentryObjCDebugMeta *> * _Nonnull images;
    [Export("images", ArgumentSemantic.Copy)]
    SentryObjCDebugMeta[] Images { get; }

    // -(NSArray<SentryObjCDebugMeta *> * _Nonnull)imagesForAddresses:(NSArray<NSNumber *> * _Nonnull)addresses;
    [Export("imagesForAddresses:")]
    SentryObjCDebugMeta[] ImagesForAddresses(NSNumber[] addresses);
}

// @interface SentryObjCInternalProfilingApi : NSObject
[BaseType(typeof(NSObject))]
[DisableDefaultCtor]
[Internal]
interface SentryObjCInternalProfilingApi
{
    // -(uint64_t)startFor:(SentryObjCId * _Nonnull)traceId;
    [Export("startFor:")]
    ulong StartFor(SentryObjCId traceId);

    // -(NSDictionary<NSString *,id> * _Nullable)collectBetweenStartTime:(uint64_t)startTime andEndTime:(uint64_t)endTime forTraceId:(SentryObjCId * _Nonnull)traceId;
    [Export("collectBetweenStartTime:andEndTime:forTraceId:")]
    [return: NullAllowed]
    NSDictionary<NSString, NSObject> CollectBetweenStartTime(ulong startTime, ulong endTime, SentryObjCId traceId);

    // -(void)discardFor:(SentryObjCId * _Nonnull)traceId;
    [Export("discardFor:")]
    void DiscardFor(SentryObjCId traceId);
}

// @interface SentryObjCInternalSdkApi : NSObject
[BaseType(typeof(NSObject))]
[DisableDefaultCtor]
[Internal]
interface SentryObjCInternalSdkApi
{
    // @property (copy, nonatomic) NSString * _Nonnull name;
    [Export("name")]
    string Name { get; set; }

    // @property (copy, nonatomic) NSString * _Nonnull versionString;
    [Export("versionString")]
    string VersionString { get; set; }

    // -(void)setName:(NSString * _Nonnull)name version:(NSString * _Nonnull)version;
    [Export("setName:version:")]
    void SetName(string name, string version);

    // -(void)addPackageName:(NSString * _Nonnull)name version:(NSString * _Nonnull)version;
    [Export("addPackageName:version:")]
    void AddPackageName(string name, string version);

    // @property (readonly, copy, nonatomic) NSDictionary<NSString *,id> * _Nonnull extraContext;
    [Export("extraContext", ArgumentSemantic.Copy)]
    NSDictionary<NSString, NSObject> ExtraContext { get; }

    // @property (readonly, copy, nonatomic) NSString * _Nonnull installationID;
    [Export("installationID")]
    string InstallationID { get; }
}

// @interface SentryObjCSDK : NSObject
[BaseType(typeof(NSObject))]
[Internal]
interface SentryObjCSDK
{

    // @property (readonly, nonatomic, class) SentryObjCInternalApi * _Nonnull internal;
    [Static]
    [Export("internal")]
    SentryObjCInternalApi Internal { get; }

    // @property (readonly, nonatomic, class) BOOL crashedLastRun __attribute__((deprecated("Use lastRunStatus instead.")));
    [Static]
    [Export("crashedLastRun")]
    bool CrashedLastRun { get; }

    // +(void)startWithOptions:(SentryObjCOptions * _Nonnull)options;
    [Static]
    [Export("startWithOptions:")]
    void StartWithOptions(SentryObjCOptions options);

    // +(void)configureScope:(void (^ _Nonnull)(SentryObjCScope * _Nonnull))callback;
    [Static]
    [Export("configureScope:")]
    void ConfigureScope(Action<SentryObjCScope> callback);

    // +(void)crash;
    [Static]
    [Export("crash")]
    void Crash();
}
