// -----------------------------------------------------------------------------
// This file is auto-generated by Objective Sharpie and patched via the script
// at /scripts/patch-cocoa-bindings.cs.  Do not edit this file directly.
// If changes are required, update the script instead.
// -----------------------------------------------------------------------------

#nullable enable

using ObjCRuntime;

namespace Sentry.CocoaSdk;

[Native]
internal enum SentryObjCAttachmentType : long
{
    EventAttachment = 0,
    ViewHierarchy
}

[Native]
internal enum SentryObjCFeedbackSource : long
{
    Widget = 0,
    Custom
}

[Native]
internal enum SentryObjCLastRunStatus : long
{
    Unknown = 0,
    DidNotCrash,
    DidCrash
}

[Native]
internal enum SentryObjCLevel : ulong
{
    None = 0,
    Debug,
    Info,
    Warning,
    Error,
    Fatal
}

[Native]
internal enum SentryObjCLogLevel : long
{
    Trace = 0,
    Debug,
    Info,
    Warn,
    Error,
    Fatal
}

[Native]
internal enum SentryObjCReplayQuality : long
{
    Low = 0,
    Medium,
    High
}

[Native]
internal enum SentryObjCSampleDecision : ulong
{
    Undecided = 0,
    Yes,
    No
}

[Native]
internal enum SentryObjCSpanStatus : ulong
{
    Undefined = 0,
    Ok,
    DeadlineExceeded,
    Unauthenticated,
    PermissionDenied,
    NotFound,
    ResourceExhausted,
    InvalidArgument,
    Unimplemented,
    Unavailable,
    InternalError,
    UnknownError,
    Cancelled,
    AlreadyExists,
    FailedPrecondition,
    Aborted,
    OutOfRange,
    DataLoss
}

[Native]
internal enum SentryObjCTransactionNameSource : long
{
    Custom = 0,
    Url,
    Route,
    View,
    Component,
    Task
}

[Native]
internal enum SentryObjCRedactRegionType : long
{
    Redact = 0,
    ClipOut,
    ClipBegin,
    ClipEnd,
    RedactSwiftUI
}

[Native]
internal enum SentryObjCSwizzleMode : long
{
    Always = 0,
    OncePerClass = 1,
    OncePerClassAndSuperclasses = 2
}
