// -----------------------------------------------------------------------------
// This file is auto-generated by Objective Sharpie and patched via the script
// at /scripts/patch-cocoa-bindings.cs.  Do not edit this file directly.
// If changes are required, update the tool instead.
// -----------------------------------------------------------------------------

using System.Runtime.InteropServices;
using Foundation;
using ObjCRuntime;
using Sentry;

namespace Sentry.CocoaSdk;

[Native]
internal enum SentryLogLevel : long
{
    None = 1,
    Error,
    Debug,
    Verbose
}

[Native]
internal enum SentryError : long
{
    UnknownError = -1,
    InvalidDsnError = 100,
    SentryCrashNotInstalledError = 101,
    InvalidCrashReportError = 102,
    CompressionError = 103,
    JsonConversionError = 104,
    CouldNotFindDirectory = 105,
    RequestError = 106,
    EventNotSent = 107,
    FileIO = 108,
    Kernel = 109
}

[Native]
internal enum SentrySampleDecision : ulong
{
    Undecided,
    Yes,
    No
}

[Native]
internal enum SentrySpanStatus : ulong
{
    Undefined,
    Ok,
    DeadlineExceeded,
    Unauthenticated,
    PermissionDenied,
    NotFound,
    ResourceExhausted,
    InvalidArgument,
    Unimplemented,
    Unavailable,
    InternalError,
    UnknownError,
    Cancelled,
    AlreadyExists,
    FailedPrecondition,
    Aborted,
    OutOfRange,
    DataLoss
}

[Native]
internal enum SentryANRType : long
{
    FatalFullyBlocking = 0,
    FatalNonFullyBlocking = 1,
    FullyBlocking = 2,
    NonFullyBlocking = 3,
    Unknown = 4
}

[Native]
internal enum SentryFeedbackSource : long
{
    Widget = 0,
    Custom = 1
}

[Native]
internal enum SentryLevel : ulong
{
    None = 0,
    Debug = 1,
    Info = 2,
    Warning = 3,
    Error = 4,
    Fatal = 5
}

[Native]
internal enum SentryStructuredLogLevel : long
{
    Trace = 0,
    Debug = 1,
    Info = 2,
    Warn = 3,
    Error = 4,
    Fatal = 5
}

[Native]
internal enum SentryProfileLifecycle : long
{
    Manual = 0,
    Trace = 1
}

[Native]
internal enum SentryReplayQuality : long
{
    Low = 0,
    Medium = 1,
    High = 2
}

[Native]
internal enum SentryReplayType : long
{
    Session = 0,
    Buffer = 1
}

[Native]
internal enum SentrySessionStatus : ulong
{
    Ok = 0,
    Exited = 1,
    Crashed = 2,
    Abnormal = 3
}

[Native]
internal enum SentryTransactionNameSource : long
{
    Custom = 0,
    Url = 1,
    Route = 2,
    View = 3,
    Component = 4,
    Task = 5
}