// -----------------------------------------------------------------------------
// This file is auto-generated by Objective Sharpie and patched via the script
// at /scripts/patch-cocoa-bindings.cs.  Do not edit this file directly.
// If changes are required, update the script instead.
// -----------------------------------------------------------------------------

#nullable enable

using System.Runtime.InteropServices;
using Foundation;
using ObjCRuntime;

namespace Sentry.CocoaSdk;

[Native]
internal enum SentryAttachmentType : long
{
    EventAttachment,
    ViewHierarchy
}

[Native]
internal enum SentryLevel : ulong
{
    None = 0,
    Debug = 1,
    Info = 2,
    Warning = 3,
    Error = 4,
    Fatal = 5
}

[Native]
internal enum SentryError : long
{
    UnknownError = -1,
    InvalidDsnError = 100,
    SentryCrashNotInstalledError = 101,
    InvalidCrashReportError = 102,
    CompressionError = 103,
    JsonConversionError = 104,
    CouldNotFindDirectory = 105,
    RequestError = 106,
    EventNotSent = 107,
    FileIO = 108,
    Kernel = 109
}

[Native]
internal enum SentrySampleDecision : ulong
{
    Undecided,
    Yes,
    No
}

[Native]
internal enum SentrySpanStatus : ulong
{
    Undefined,
    Ok,
    DeadlineExceeded,
    Unauthenticated,
    PermissionDenied,
    NotFound,
    ResourceExhausted,
    InvalidArgument,
    Unimplemented,
    Unavailable,
    InternalError,
    UnknownError,
    Cancelled,
    AlreadyExists,
    FailedPrecondition,
    Aborted,
    OutOfRange,
    DataLoss
}

[Native]
internal enum SentryAppStartType : ulong
{
    Warm,
    Cold,
    Unknown
}

[Native]
internal enum SentryANRType : long
{
    FatalFullyBlocking = 0,
    FatalNonFullyBlocking = 1,
    FullyBlocking = 2,
    NonFullyBlocking = 3,
    Unknown = 4
}

[Native]
internal enum SentryDataCategory : ulong
{
    All = 0,
    Default = 1,
    Error = 2,
    Session = 3,
    Transaction = 4,
    Attachment = 5,
    UserFeedback = 6,
    Profile = 7,
    MetricBucket = 8,
    Replay = 9,
    ProfileChunkUI = 10,
    Span = 11,
    Feedback = 12,
    LogItem = 13,
    TraceMetric = 14,
    LogByte = 15,
    TraceMetricByte = 16,
    Unknown = 17
}

[Native]
internal enum SentryDiscardReason : ulong
{
    BeforeSend = 0,
    EventProcessor = 1,
    SampleRate = 2,
    NetworkError = 3,
    QueueOverflow = 4,
    CacheOverflow = 5,
    RateLimitBackoff = 6,
    InsufficientData = 7,
    SendError = 8
}

[Native]
internal enum SentryExtensionType : long
{
    Widget = 0,
    Intent = 1,
    Action = 2,
    Share = 3,
    NotificationService = 4
}

[Native]
internal enum SentryFeedbackSource : long
{
    Widget = 0,
    Custom = 1
}

[Native]
internal enum SentryFlushResult : long
{
    Success = 0,
    TimedOut = 1,
    AlreadyFlushing = 2
}

[Native]
internal enum SentryHttpStatusCode : long
{
    Ok = 200,
    Created = 201,
    BadRequest = 400,
    PreconditionFailed = 412,
    ContentTooLarge = 413,
    TooManyRequests = 429,
    InternalServerError = 500
}

[Native]
internal enum SentryLastRunStatus : long
{
    Unknown = 0,
    DidNotCrash = 1,
    DidCrash = 2
}

[Native]
internal enum SentryLogLevel : long
{
    Trace = 0,
    Debug = 1,
    Info = 2,
    Warn = 3,
    Error = 4,
    Fatal = 5
}

[Native]
internal enum SentryProfileLifecycle : long
{
    Manual = 0,
    Trace = 1
}

[Native]
internal enum SentryReplayQuality : long
{
    Low = 0,
    Medium = 1,
    High = 2
}

[Native]
internal enum SentryReplayType : long
{
    Session = 0,
    Buffer = 1
}

[Native]
internal enum SentryTransactionNameSource : long
{
    Custom = 0,
    Url = 1,
    Route = 2,
    View = 3,
    Component = 4,
    Task = 5
}
