name: Setup .NET for Sentry
runs:
  using: composite

  steps:

    - name: Set Global Environment Variables
      shell: bash
      run: |
        echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV
        echo "DOTNET_NOLOGO=1" >> $GITHUB_ENV

    - name: Install .NET 2.1 SDK
      uses: actions/setup-dotnet@v2
      env:
        # Prevent setup-dotnet action from stepping on pre-installed dotnet SDKs on Ubuntu and Windows (doesn't happen on macOS)
        DOTNET_INSTALL_DIR: ${{ startsWith(runner.os, 'Linux') && '/usr/share/dotnet' || startsWith(runner.os, 'Windows') && 'C:\Program Files\dotnet' || '' }}
      with:
        dotnet-version: 2.1.818
        # All other versions of .NET we need are pre-installed on the GitHub Actions virtual images.

    - name: Dependency Caching
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        # We don't use a lockfile, so hash all files where we might be keeping <PackageReference> tags.
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.*proj', '**/*.props') }}
        restore-keys: ${{ runner.os }}-nuget

    # TODO: Figure out how to cache workloads, as they're not quite the same as nuget packages.
    - name: Install .NET Workloads
      shell: bash
      run: |
        dotnet workload install \
          maui-android \
          {{ startsWith(runner.os, 'macOS') && 'maui-ios maui-maccatalyst' || '' }} \
          {{ startsWith(runner.os, 'Windows') && 'maui-windows' || '' }} \
          --temp-dir "${{ runner.temp }}"
