name: 🐞 Bug Report
description: Tell us about something that's not working the way we (probably) intend.
labels: ["Platform: .NET", "bug"]
body:
  - type: dropdown
    id: nuget
    attributes:
      description: NuGet Package
      label: Package
      options:
        - Sentry
        - Sentry.AspNetCore
        - Sentry.AspNetCore.Grpc
        - Sentry.AspNet
        - Sentry.EntityFramework
        - Sentry.Google.Cloud.Functions
        - Sentry.DiagnosticSource
        - Sentry.Serilog
        - Sentry.Nlog
        - Sentry.Log4net
        - Sentry.Extensions.Logging
        - Sentry.Tunnel
        - Other
    validations:
      required: true

  - type: dropdown
    id: dotnet_flavor
    attributes:
      description: .NET Flavor
      label: .NET Flavor
      options:
        - .NET
        - .NET Core
        - .NET Framework
        - Mono
        - Xamarin
        - IL2CPP
        - Other
    validations:
      required: true

  - type: input
    id: dotnet_version
    attributes:
      label: .NET Version
      description: .NET Version
      placeholder: 6.0.0 ← should look like this
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      description: Operating System
      options:
        - Windows
        - Linux
        - macOS
        - Android
        - iOS
        - Browser
        - Other
    validations:
      required: true

  - type: input
    id: sentry_sdk_version
    attributes:
      label: SDK Version
      description: Sentry SDK Version
      placeholder: 6.0.0 ← should look like this
    validations:
      required: true

  - type: input
    id: sentry_version
    attributes:
      label: Self-Hosted Sentry Version
      description: Leave blank if using sentry.io
    validations:
      required: false

  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: How can we see what you're seeing? Specific is terrific.
      placeholder: |-
        1. foo
        2. bar
        3. baz
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Result
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: Logs? Screenshots?
    validations:
      required: true

  - type: markdown
    attributes:
      value: |-
        ## Thanks 🙏
        Check our [triage docs](https://open.sentry.io/triage/) for what to expect next.
