name: 🐞 Bug Report
description: Tell us about something that's not working the way we (probably) intend.
labels: ["Platform: .NET", "bug"]
body:
  - type: dropdown
    id: nuget
    attributes:
      description: NuGet Package
      label: Package
      options:
        - Sentry
        - Sentry.AspNetCore
        - Sentry.AspNetCore.Grpc
        - Sentry.AspNet
        - Sentry.DiagnosticSource
        - Sentry.EntityFramework
        - Sentry.Extensions.Logging
        - Sentry.Google.Cloud.Functions
        - Sentry.Log4net
        - Sentry.Maui
        - Sentry.Nlog
        - Sentry.Serilog
        - Sentry.Tunnel
        - Other
    validations:
      required: true

  - type: dropdown
    id: dotnet_flavor
    attributes:
      description: .NET Flavor
      label: .NET Flavor
      options:
        - .NET
        - .NET Core
        - .NET Framework
        - IL2CPP
        - Mono
        - Other
    validations:
      required: true

  - type: input
    id: dotnet_version
    attributes:
      label: .NET Version
      description: If using .NET Core, please copy the output of 'dotnet --version' here
      placeholder: 9.0.200 ← should look like this
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: OS
      description: Operating System
      options:
        - Android
        - Browser
        - macOS
        - iOS
        - Linux
        - Windows
        - Any (not platform specific)
        - Other
    validations:
      required: true

  - type: input
    id: os_version
    attributes:
      label: OS Version
      description: Operating System Version

  - type: dropdown
    id: ide
    attributes:
      label: Development Environment
      description: What development environment are you using
      options:
        - Visual Studio v17.x
        - Visual Studio Code (Windows)
        - Visual Studio Code (MacOS)
        - Rider 2024 (Windows)
        - Rider 2024 (MacOS)
        - Other
    validations:
      required: true

  - type: input
    id: sentry_sdk_version
    attributes:
      label: SDK Version
      description: Sentry SDK Version
      placeholder: 6.0.0 ← should look like this
    validations:
      required: true

  - type: input
    id: sentry_version
    attributes:
      label: Self-Hosted Sentry Version
      description: Leave blank if using sentry.io
    validations:
      required: false

  - type: textarea
    id: workloadset
    attributes:
      label: Workload Versions
      description: If using .NET Core, please copy/paste the output of 'dotnet workload list' here
    validations:
      required: true

  - type: textarea
    id: sentryuse
    attributes:
      label: UseSentry or SentrySdk.Init call
      description: Please include the block of code used in UseSentry or SentrySdk.Init - please blank out your DSN
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Steps to Reproduce
      description: How can we see what you're seeing? Specific is terrific.
      placeholder: |-
        1. foo
        2. bar
        3. baz
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Result
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: Logs? Screenshots?
    validations:
      required: true

  - type: markdown
    attributes:
      value: |-
        ## Thanks 🙏
        Check our [triage docs](https://open.sentry.io/triage/) for what to expect next.
