namespace Sentry;

/// <summary>
/// Constants used to name Hints generated by the Sentry SDK
/// </summary>
public static class HintTypes
{
    /// <summary>
    /// Used for HttpResponseMessage hints
    /// </summary>
    public const string HttpResponseMessage = "http-response-message";
}
