namespace Sentry;

/// <summary>
/// Immutable data belonging to a transaction.
/// </summary>
public interface ITransactionData : ISpanData, ITransactionContext, IEventLike
{
    /// <summary>
    /// The name of the platform.
    /// </summary>
    /// <remarks>
    /// In most cases, the platform will be "csharp". However, it may differ if the event
    /// was generated from another embeded SDK.  For example, when targeting net6.0-android,
    /// events generated by the Sentry Android SDK will have the platform "java".
    /// </remarks>
    public string? Platform { get; set; }
}
