<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(CurrentTfms)</TargetFrameworks>
    <Nullable>enable</Nullable>
    <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('Windows'))">$(TargetFrameworks);net48</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Sentry.Quartz\Sentry.Quartz.csproj" />
    <ProjectReference Include="..\Sentry.Testing\Sentry.Testing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Quartz" />
  </ItemGroup>

</Project>
