using System;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace Sentry.SourceGenerators;


/// <summary>
/// Generates the necessary msbuild variables
/// </summary>
[Generator(LanguageNames.CSharp)]
public class BuildPropertySourceGenerator : ISourceGenerator
{
    /// <summary>
    /// Initialize the source gen
    /// </summary>
    public void Initialize(GeneratorInitializationContext context)
    {
    }

    /// <summary>
    /// Execute the source gen
    /// </summary>
    public void Execute(GeneratorExecutionContext context)
    {
        var opts = context.AnalyzerConfigOptions.GlobalOptions;
        var properties = opts.Keys.Where(x => x.StartsWith("build_property.")).ToList();
        if (properties.Count == 0)
            return;

        if (opts.TryGetValue("build_property.SentryDisableSourceGenerator", out var disable) && disable.Equals("true", StringComparison.InvariantCultureIgnoreCase))
            return;

        // we only want to generate code where host setup takes place
        if (!opts.TryGetValue("build_property.outputtype", out var outputType))
            return;

        if (!outputType.Equals("exe", StringComparison.InvariantCultureIgnoreCase))
            return;

        var sb = new StringBuilder();
        sb
            .Append(
"""
// <auto-generated>
// Code generated by Sentry Source Generators
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

#if NET8_0_OR_GREATER
using System;
using System.Collections.Generic;

namespace Sentry;

[global::System.Runtime.CompilerServices.CompilerGenerated]
public static class BuildVariableInitializer
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    public static void Initialize()
    {
        global::Sentry.CompilerServices.BuildProperties.Initialize(new global::System.Collections.Generic.Dictionary<string, string> {

"""
            );

        foreach (var property in properties)
        {
            if (opts.TryGetValue(property, out var value))
            {
                var pn = EscapeString(property.Replace("build_property.", ""));
                var ev = EscapeString(value);
                sb
                    .Append("\t\t\t{")
                    .Append($"\"{pn}\", \"{ev}\"")
                    .AppendLine("},");
            }
        }

        sb
            .AppendLine("\t\t});") // close dictionary
            .AppendLine("\t}")
            .AppendLine("}")
            .AppendLine("#endif");

        context.AddSource("__BuildProperties.g.cs", sb.ToString());
    }


    private static string EscapeString(string value) => value.Replace("\\", "\\\\");
}
