name: Setup Environment
description: Sets env vars and installs dependencies
runs:
  using: composite

  steps:

    - name: Set Global Environment Variables
      shell: bash
      run: |
        echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV
        echo "DOTNET_NOLOGO=1" >> $GITHUB_ENV

    # Android SDK Tools are arm64-incompatible
    # Android SDK Build Tools are musl-incompatible
    - name: Set Environment Variables for Alpine Linux
      if: ${{ (runner.os == 'Linux' && runner.arch == 'ARM64') || contains(matrix.container, 'alpine') }}
      shell: bash
      run: echo "NO_MOBILE=true" >> $GITHUB_ENV

    # zstd is needed for cross OS actions/cache but missing from windows-11-arm
    # https://github.com/actions/partner-runner-images/issues/99
    - name: Install zstd on Windows ARM64
      if: runner.os == 'Windows' && runner.arch == 'ARM64'
      shell: pwsh
      run: choco install zstandard

    # See https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md#xcode
    - name: Pin the Xcode Version
      if: runner.os == 'macOS'
      shell: bash
      run: sudo xcode-select --switch /Applications/Xcode_16.2.app

    # Java 17 is needed for Android SDK setup step
    - name: Install Java 17
      if: ${{ !matrix.container }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' && 'microsoft' || 'temurin' }}
        java-version: '17'

    - name: Setup Android SDK
      if: ${{ (runner.os != 'Linux' || runner.arch != 'ARM64') && !matrix.container }}
      uses: android-actions/setup-android@07976c6290703d34c16d382cb36445f98bb43b1f # v3.2.0
      with:
        log-accepted-android-sdk-licenses: false

    # Java 11 is needed by .NET Android
    - name: Install Java 11
      if: ${{ !matrix.container }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' && 'microsoft' || 'temurin' }}
        java-version: '11'

    - name: Install Mono
      if: runner.os == 'macOS'
      shell: bash
      # Attempt to install Mono, allowing it to fail silently
      # Then ensure mono is correctly linked, overwriting any conflicting symlinks
      run: |
        brew install mono || true
        brew link --overwrite mono

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.301

    - name: Install .NET Workloads
      shell: bash
      run: |
        pwd
        dotnet workload install \
          wasm-tools wasm-tools-net8 maui-android android mobile-librarybuilder \
          ${{ runner.os == 'macOS' && 'maui-ios maui-maccatalyst maui-windows macos' || '' }} \
          ${{ runner.os == 'Windows' && 'maui-ios maui-maccatalyst maui-windows' || '' }} \
          --temp-dir "${{ runner.temp }}" \
          --skip-sign-check
