name: Setup Environment
description: Sets env vars and installs dependencies
runs:
  using: composite

  steps:

    - name: Set Global Environment Variables
      shell: bash
      run: |
        echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV
        echo "DOTNET_NOLOGO=1" >> $GITHUB_ENV

    # Needed for Android SDK setup step
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@07976c6290703d34c16d382cb36445f98bb43b1f # v3.2.0
      with:
        log-accepted-android-sdk-licenses: false

    - name: Set Java Version
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    # .NET 6 and .NET 8 are not built-in with macos-13
    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x
          9.0.100-rc.2.24474.11

    - name: Install .NET Workloads
      shell: bash
      run: >
        dotnet workload install \
          wasm-tools maui-android \
          ${{ runner.os == 'macOS' && 'maui-ios maui-maccatalyst maui-windows macos' || '' }} \
          ${{ runner.os == 'Windows' && 'maui-windows' || '' }} \
          --temp-dir "${{ runner.temp }}" \
          --skip-sign-check
