name: Setup Environment
description: Sets env vars and installs dependencies
runs:
  using: composite

  steps:

    - name: Set Global Environment Variables
      shell: bash
      run: |
        echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV
        echo "DOTNET_NOLOGO=1" >> $GITHUB_ENV

    - name: Set Java Version
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    # .NET 3.1 has been removed from all OS due to EOL
    # https://github.com/actions/runner-images/issues/7667
    - name: Install .NET 3.1 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x

    - name: Install .NET 7 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Install .NET 8 SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Dependency Caching
      uses: actions/cache@v3
      # Cache is too slow on Windows to be useful.  See https://github.com/actions/cache/issues/752
      if: runner.os != 'Windows'
      with:
        path: ~/.nuget/packages
        # We don't use a lockfile, so hash all files where we might be keeping <PackageReference> tags.
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.*proj', '**/*.props') }}
        restore-keys: ${{ runner.os }}-nuget

    # TODO: Figure out how to cache workloads, as they're not quite the same as nuget packages.
    - name: Install .NET Workloads
      shell: bash
      run: >
        dotnet workload install \
          maui-android \
          ${{ runner.os == 'macOS' && 'maui-ios maui-maccatalyst maui-windows maui-tizen' || '' }} \
          ${{ runner.os == 'Windows' && 'maui-windows' || '' }} \
          --temp-dir "${{ runner.temp }}" --from-rollback-file rollback.json

    # We build Sentry.Maui for every supported MAUI target so we can access platform-specific features.
    # That includes Tizen. We don't need the entire Tizen SDK, but we do need the base Tizen workload.
    # Though we could install it on all runners, we really only need it when building and packing for NuGet, which we do on macOS only.
    - name: Install Tizen Workload
      if: runner.os == 'macOS'
      shell: bash
      run: "curl -sSL https://raw.githubusercontent.com/Samsung/Tizen.NET/main/workload/scripts/workload-install.sh | sudo bash"
