name: Setup Environment
description: Sets env vars and installs dependencies
runs:
  using: composite

  steps:

    - name: Set Global Environment Variables
      shell: bash
      run: |
        echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV
        echo "DOTNET_NOLOGO=1" >> $GITHUB_ENV

    # See https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md#xcode
    - name: Pin the Xcode Version
      if: runner.os == 'macOS'
      shell: bash
      run: sudo xcode-select --switch /Applications/Xcode_16.2.app

    # Needed for Android SDK setup step
    - uses: actions/setup-java@v3
      if: runner.os != 'Windows' && runner.arch != 'ARM64'
      with:
        distribution: 'temurin'
        java-version: '17'

    - uses: actions/setup-java@v3
      if: runner.os == 'Windows' && runner.arch == 'ARM64'
      with:
        distribution: 'temurin'
        # Error: Could not find satisfied version for SemVer '17'. 
        # Available versions: 23.0.2+7, 23.0.1+11, 21.0.7+6.0.LTS, 21.0.6+7.0.LTS, 21.0.5+11.0.LTS
        java-version: '21'

    - name: Setup Android SDK
      uses: android-actions/setup-android@07976c6290703d34c16d382cb36445f98bb43b1f # v3.2.0
      with:
        log-accepted-android-sdk-licenses: false

    # https://github.com/actions/runner-images/issues/10814
    - name: Workaround build-tools issue
      if: runner.os == 'macOS'
      shell: bash
      run: |
        curl https://dl.google.com/android/repository/build-tools_r35_macosx.zip > $ANDROID_HOME/build-tools_r35_macosx.zip
        cd $ANDROID_HOME
        mkdir -p build-tools
        unzip build-tools_r35_macosx.zip
        mv android-15 build-tools/35.0.0
        cd -

    - name: Install Mono
      if: runner.os == 'macOS'
      shell: bash
      # Attempt to install Mono, allowing it to fail silently
      # Then ensure mono is correctly linked, overwriting any conflicting symlinks
      run: |
        brew install mono || true
        brew link --overwrite mono

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.203

    - name: Install .NET Workloads
      shell: bash
      run: |
        pwd
        dotnet workload install \
          wasm-tools wasm-tools-net8 maui-android \
          ${{ runner.os == 'macOS' && 'maui-ios maui-maccatalyst maui-windows macos' || '' }} \
          ${{ runner.os == 'Windows' && 'maui-ios maui-maccatalyst maui-windows' || '' }} \
          --temp-dir "${{ runner.temp }}" \
          --skip-sign-check
