name: Setup Environment
description: Sets env vars and installs dependencies
runs:
  using: composite

  steps:

    - name: Set Global Environment Variables
      shell: bash
      run: |
        echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV
        echo "DOTNET_NOLOGO=1" >> $GITHUB_ENV

    # See https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md#xcode
    - name: Pin the Xcode Version
      if: runner.os == 'macOS'
      shell: bash
      run: sudo xcode-select --switch /Applications/Xcode_16.2.app

    # Java 17 is needed for Android SDK setup step
    - name: Install Java 17
      uses: actions/setup-java@v3
      if: runner.os != 'Windows' && runner.arch != 'ARM64'
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Java 17 on Windows ARM64
      if: runner.os == 'Windows' && runner.arch == 'ARM64'
      shell: bash
      run: |
        curl -LO https://download.bell-sw.com/java/17.0.10+7/bellsoft-jdk17.0.10+7-windows-aarch64.zip
        unzip bellsoft-jdk17.0.10+7-windows-aarch64.zip -d jdk17
        echo "${{ github.workspace }}/jdk17/bellsoft-jdk17.0.10+7-windows-aarch64/bin" >> $GITHUB_PATH


    - name: Setup Android SDK
      uses: android-actions/setup-android@07976c6290703d34c16d382cb36445f98bb43b1f # v3.2.0
      with:
        log-accepted-android-sdk-licenses: false

    # Java 11 is needed by .NET Android
    # - name: Install Java 11
    #   if: runner.os != 'Windows' && runner.arch != 'ARM64'
    #   uses: actions/setup-java@v3
    #   with:
    #     distribution: 'temurin'
    #     java-version: '11'

    - name: Install Java 11 # on Windows ARM64
      # if: runner.os == 'Windows' && runner.arch == 'ARM64'
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '11'

    - name: Install Mono
      if: runner.os == 'macOS'
      shell: bash
      # Attempt to install Mono, allowing it to fail silently
      # Then ensure mono is correctly linked, overwriting any conflicting symlinks
      run: |
        brew install mono || true
        brew link --overwrite mono

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.203

    - name: Install .NET Workloads
      shell: bash
      run: |
        pwd
        dotnet workload install \
          wasm-tools wasm-tools-net8 maui-android \
          ${{ runner.os == 'macOS' && 'maui-ios maui-maccatalyst maui-windows macos' || '' }} \
          ${{ runner.os == 'Windows' && 'maui-ios maui-maccatalyst maui-windows' || '' }} \
          --temp-dir "${{ runner.temp }}" \
          --skip-sign-check
