name: Setup Environment
description: Sets env vars and installs dependencies
runs:
  using: composite

  steps:

    - name: Set Global Environment Variables
      shell: bash
      run: |
        echo "DOTNET_CLI_TELEMETRY_OPTOUT=1" >> $GITHUB_ENV
        echo "DOTNET_NOLOGO=1" >> $GITHUB_ENV

    # Android SDK Tools are arm64-incompatible
    # Android SDK Build Tools are musl-incompatible
    - name: Set Environment Variables for Alpine Linux
      if: ${{ (runner.os == 'Linux' && runner.arch == 'ARM64') || contains(matrix.container.image, 'alpine') }}
      shell: bash
      run: echo "NO_MOBILE=true" >> $GITHUB_ENV

    # Allow sudoless Docker in integration tests
    - name: Prepare Docker on Alpine Linux
      if: ${{ contains(matrix.container.image, 'alpine') }}
      shell: bash
      run: sudo chmod 666 /var/run/docker.sock

    - name: Install Linux ARM 32-bit dependencies
      if: ${{ matrix.rid == 'linux-arm' }}
      shell: bash
      run: |
        sudo dpkg --add-architecture armhf
        sudo apt-get update
        sudo apt-get install -y gcc-arm-linux-gnueabihf libc6:armhf

    # zstd is needed for cross OS actions/cache but missing from windows-11-arm
    # https://github.com/actions/partner-runner-images/issues/99
    - name: Install zstd on Windows ARM64
      uses: ./.github/actions/install-zstd

    # See https://github.com/actions/runner-images/blob/main/images/macos/macos-15-Readme.md#xcode
    - name: Pin the Xcode Version
      if: runner.os == 'macOS'
      shell: bash
      run: sudo xcode-select --switch /Applications/Xcode_16.4.app

    # Java 17 is needed for Android SDK setup step
    - name: Install Java 17
      if: ${{ !matrix.container }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' && 'microsoft' || 'temurin' }}
        java-version: '17'

    - name: Setup Android SDK
      if: ${{ !matrix.container }}
      uses: android-actions/setup-android@07976c6290703d34c16d382cb36445f98bb43b1f # v3.2.0
      with:
        # Exclude "tools" because the emulator is not needed (nor available for Windows/Linux ARM64)
        packages: platform-tools platforms;android-34 platforms;android-35 build-tools;36.0.0
        log-accepted-android-sdk-licenses: false

    # Java 11 is needed by .NET Android
    - name: Install Java 11
      if: ${{ !matrix.container }}
      uses: actions/setup-java@v4
      with:
        distribution: ${{ runner.os == 'Windows' && runner.arch == 'ARM64' && 'microsoft' || 'temurin' }}
        java-version: '11'

    - name: Install Mono
      if: runner.os == 'macOS'
      shell: bash
      # Attempt to install Mono, allowing it to fail silently
      # Then ensure mono is correctly linked, overwriting any conflicting symlinks
      run: |
        brew install mono || true
        brew link --overwrite mono

    - name: Install .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.301

    - name: Install .NET Workloads
      shell: bash
      run: |
        pwd
        dotnet workload restore \
          --temp-dir "${{ runner.temp }}" \
          --skip-sign-check
