name: Build Native Dependencies
description: Builds Sentry Cocoa SDK with custom Carthage
runs:
  using: composite

  steps:
    - name: Cache Sentry Cocoa SDK
      id: cache-sentry-cocoa
      uses: actions/cache@v3
      with:
        path: modules/sentry-cocoa/Carthage
        key: sentry-cocoa-${{ hashFiles('scripts/build-sentry-cocoa.sh') }}-${{ hashFiles('.git/modules/modules/sentry-cocoa/HEAD') }}

    - name: Build Sentry Cocoa SDK
      if: ${{ steps.cache-sentry-cocoa.outputs.cache-hit != 'true' }}
      shell: bash
      run: scripts/build-sentry-cocoa.sh
