name: Require Changelog

on: [pull_request]

jobs:
  check:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ensure Changelog.md was modified
        shell: pwsh
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1 -q

          $merge_base = git merge-base ${{ github.head_ref }} ${{ github.base_ref }}

          $changes = git --no-pager diff --name-only ${{ github.head }} $merge_base
          echo $changes

          $contains_changelog = $changes -split '\n' -contains 'CHANGELOG.md'

          if (-not $contains_changelog) {
            echo '::error::Changelog has not been modified!'
            exit 1
          }

          exit 0
