name: Changelog Preview
on:
  pull_request_target:
    types:
    - opened
    - synchronize
    - reopened
    - edited
    - labeled
    - unlabeled
permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  changelog-preview:
    if: false
    uses: getsentry/craft/.github/workflows/changelog-preview.yml@2d78918ece86d970404ccaa029735cb5dce1901b # 2.26.0
    secrets: inherit
