name: Changelog Preview
on:
  pull_request_target:
    types:
    - opened
    - synchronize
    - reopened
    - edited
    - labeled
    - unlabeled
permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  changelog-preview:
    if: false
    uses: getsentry/craft/.github/workflows/changelog-preview.yml@9312e4dfc82e545ef0cad911c23f430fe5f52673 # 2.26.12
    secrets: inherit
