name: Require changelog entry

on: [pull_request]

jobs:
  check:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ensure Changelog.md was modified
        shell: pwsh
        run: |
          git fetch origin ${{ github.base_ref }}

          $merge_base = git merge-base ${{ github.head_ref }} ${{ github.base_ref }}

          $changes = git --no-pager diff --name-only FETCH_HEAD $merge_base
          $contains_changelog = $changes -contains 'CHANGELOG.md'

          if (-not $contains_changelog) {
            echo '::error::Changelog has not been modified!'
            exit 1
          }

          exit 0
