name: Update Dependencies

on:
  # Run every day.
  schedule:
    - cron: "0 3 * * *"
  # And on every PR merge so we get the updated dependencies ASAP, and to make sure the changelog doesn't conflict.
  push:
    branches:
      - main
  # Allow a manual trigger to be able to run the update when there are new dependencies or after a PR merge to resolve CHANGELOG conflicts.
  workflow_dispatch:

permissions:
  contents: write      # To modify files and create commits
  pull-requests: write # To create and update pull requests
  actions: write       # To cancel previous workflow runs

jobs:
  deps:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Cocoa SDK
            path: modules/sentry-cocoa
          - name: Java SDK
            path: scripts/update-java.ps1
          - name: Native SDK
            path: modules/sentry-native
          - name: CLI
            path: scripts/update-cli.ps1
    steps:
      - uses: getsentry/github-workflows/updater@26f565c05d0dd49f703d238706b775883037d76b # 3.3.0
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.path }}
          ssh-key: ${{ secrets.CI_DEPLOY_KEY }}
          changelog-entry: false
